### ISSUE TITLE
Bloated Character Setup

### ISSUE THREAD

**Issue by Locating** [FTL13/FTL13#100]
**Problem Description**:
The character setup screen gets bloated with the character preview when you repeatedly click "Setup Character" in new player options.

**What did you expect to happen**: 
I expected to open the character setup screen with no anomalies.

**What happened instead**:
What I described, it seemed to get bigger with each click.

**Why is this bad/What are the consequences:**
I guess It's not THAT important, closing and opening the character setup seemed to fix it.

**Steps to reproduce the problem**:
Again, click the "setup character" button a lot.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
I had just joined. I've attached a picture of how it looks.
![ftl station character bug](https://cloud.githubusercontent.com/assets/20954280/17563334/940a2754-5ef4-11e6-8ccf-229b5fd930af.png)

**Comment by CrAzYPiLoT-SS13** [comment]
More in-depth explanation: #62
