### ISSUE TITLE
No "combat text" for AI player when in ship to ship combat.

### ISSUE THREAD

**Issue by Ecolli** [FTL13/FTL13#103]
**Problem Description**:
No hit/miss info when playing as the AI.

**What did you expect to happen**: 
Why do you think this is a bug?

**What happened instead**:
How is what happened different from what you expected?

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Vivalas** [comment]
Do you mean the AI doesn't get messages when the eye is in range of a scanner console?

**Comment by Ecolli** [comment]
Yeah i was playing as AI and we were shooting at an enemy ship but i wasn't getting "hit messages" or anything like that. 

    On Wednesday, August 10, 2016 7:51 PM, Vivalas <notifications@github.com> wrote:
 

 Do you mean the AI doesn't get messages when the eye is in range of a scanner console? —

**Comment by CrAzYPiLoT-SS13** [comment]
Are you sure this happens? I just checked over the whole system, and it seems to be working fine. I haven't tested in-game, though.

**Comment by Ecolli** [comment]
Space Station 13 | FTL13 | A Round to remember |   Watch around 47 minutes in, we are taking fire...there are atmos system alarms but thats it. not the normal combat text humans see during ship combat. 

|   |
|   |  |   |   |   |   |   |
| Space Station 13 | FTL13 | A Round to remember | |
|  |
| View on www.youtube.com | Preview by Yahoo |
|  |
|   |


 

    On Monday, August 29, 2016 2:54 AM, CrAzYPiLoT-SS13 <notifications@github.com> wrote:
 

 Are you sure this happens? I just checked over the whole system, and it seems to be working fine. I haven't tested in-game, though.—
