### ISSUE TITLE
Borg Stuttering

### ISSUE THREAD

**Issue by MASMC** [FTL13/FTL13#1041]
[Note]: # (Please enter the commit hash and active testmerge numbers from the "Show Server Revision" verb if you can. If you believe the issue to be caused by a testmerge, please report it in its relative PR thread. State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))
Uhh... right before rebase? "Revision unknown"

SO. Borgs should not be able to stutter? It won't happen normally. You gotta BSA them first. Then they get the stammer effects, seeming like it is hardcoded into BSA to make that happen. Happened while Draycu was hosting for his map.

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by ike709** [comment]
Bugs resulting from badminnery are probably the lowest priority bugs in existence.

Also making issues for pre-rebase code is silly and pointless.

**Comment by MASMC** [comment]
/shrug No idea if it is in new /tg/

**Comment by ninjanomnom** [comment]
Code is completely different around this and it barely counts as a bug
