### ISSUE TITLE
Chat has a space after the opening quotation mark and before the closing quotation mark

### ISSUE THREAD

**Issue by ike709** [FTL13/FTL13#1073]
![image](https://user-images.githubusercontent.com/5714543/27117812-f09b5510-509d-11e7-9406-7fdf1a2149b4.png)

I'm not sure if it's intentional or not but it looks weird and I don't like it.

**Comment by Funce** [comment]
![image](https://user-images.githubusercontent.com/14105827/27264930-f96f884c-54de-11e7-81b0-2e8bf1c3388a.png)
This doesn't seem to be a problem anymore.

**Comment by Kmsxkuse** [comment]
I never noticed it in any of my testing. I think it's fixed.
