### ISSUE TITLE
The ship is randomly named

### ISSUE THREAD

**Issue by ike709** [FTL13/FTL13#1075]
![image](https://user-images.githubusercontent.com/5714543/27117913-73029798-509e-11e7-93cb-604f9e1413ce.png)

Probably a config option

**Comment by Kmsxkuse** [comment]
A surface level fix, line 60 of \code\__HELPERS\names.dm.
if(config && config.station_name) to if(config.station_name).
It works but this brings up a problem that station_name() is being called before config is created roughly 3 times, which is not suppose to happen.

My beginner level bug fixing revealed a much bigger problem. RIP my bug fix.
