### ISSUE TITLE
Station goals

### ISSUE THREAD

**Issue by ike709** [FTL13/FTL13#1076]
![image](https://user-images.githubusercontent.com/5714543/27117926-83827e08-509e-11e7-80bc-a9ac57980bb4.png)

- [x] ~~They're called "station"~~ #1300
- [ ] They need to be modified to fit FTL13. For example, the "station shield" one is irrelevant when we have a shield already.
- [ ] There isn't a way to check mid round to see what the goals are?
- [ ] I doubt completion detection works, but it might.

**Comment by Qustinnus** [comment]
why not just remove them or replace them with the FTL related stuff
