### ISSUE TITLE
Station Goals

### ISSUE THREAD

**Issue by MASMC** [FTL13/FTL13#1077]
[Note]: # (Please enter the commit hash and active testmerge numbers from the "Show Server Revision" verb if you can. If you believe the issue to be caused by a testmerge, please report it in its relative PR thread. State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

Server revision compiled on:  2017-06-13 

646759 

We are not a station, we are a ship. We could rename them or we could take 'em away, but...
![image](https://user-images.githubusercontent.com/9438930/27117972-0ed2eb98-50a7-11e7-8f8d-a582f1e60b8b.png)

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by ike709** [comment]
Dupe of my issue.

**Comment by MASMC** [comment]
Ike, you were SLIGHTLY ahead. Shush.
