### ISSUE TITLE
AI vision bug

### ISSUE THREAD

**Issue by Nickthemoonwolf** [FTL13/FTL13#1079]
[Note]: # (Please enter the commit hash and active testmerge numbers from the "Show Server Revision" verb if you can. If you believe the issue to be caused by a testmerge, please report it in its relative PR thread. State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

646759
The vision of the AI (from my end, at least) starts perfectly when docked, and then cuts to static in seemingly random locations of the ship, usually including massive chunks of the ship. These areas appear identical to all areas that the AI does not have camera access to; Floors and plating.
The only thing I can tell is that being in orbit causes it, and until it broke, being in FTL (sometimes, somewhat) would fix it.

![1](https://user-images.githubusercontent.com/29422731/27118651-e1a9aa4e-50a1-11e7-98f4-76ce082941d6.png)
Initially, this is the view I had for most of the northern part of the station. 

![4](https://user-images.githubusercontent.com/29422731/27118690-123c14b2-50a2-11e7-9256-b53d8973d3c9.png)
For a while, restarting my client would at least change where I can see. After a while it stopped working, and this is an example of what I was left with. 

![5](https://user-images.githubusercontent.com/29422731/27118729-36a78f98-50a2-11e7-8563-d6f3f6eb0370.png)
 Another example of how strange and random this seems to be. 

![6](https://user-images.githubusercontent.com/29422731/27118904-1dd996c2-50a3-11e7-9d34-a5fa1541d89a.png)
Final example
As a note, this may be caused by the lighting subsystem not loading or having errors.

**Comment by ninjanomnom** [comment]
Likely this can fairly easily be fixed by giving cameras, AI, or both onMove procs to re initialize the camera networks.

**Comment by ninjanomnom** [comment]
Not as easily fixed as I thought on basic inspection. It seems that cameranet chunks aren't being handled correctly in map unloading.

**Comment by Nickthemoonwolf** [comment]
Can confirm that this is not fixed yet.
