### ISSUE TITLE
Ships just won't die.

### ISSUE THREAD

**Issue by dannyy3566** [FTL13/FTL13#1086]
Syndie Bulker, patrol drone x5, syndie skirmisher x2, all with hull and shields 0.
tried a sdql2 query of: DELETE /datum/starship IN SSstarmap.current_system.ships;
Did nothing. Ships are still bombing the hell out of the players. I have no idea how this happened.
As an aside, the admin logs say the ships are dying every time they get shot.

**Comment by Altangy** [comment]
I'd like to also add this to the issue as evidence 
![image](https://user-images.githubusercontent.com/25562238/27148328-d5ff1dca-510d-11e7-8e3e-03d9b50aa376.png)

**Comment by Qustinnus** [comment]
were the ships actually in your current system? sounds to me like if current.system.ships doesnt works, that probably means they werent in the current system.

**Comment by dannyy3566** [comment]
@qustinnus "Ships are still bombing the hell out of the players."

**Comment by Qustinnus** [comment]
yes i realize what you wrote. Do you realize bugs can cause ships to attack you from other systems? You're not answering my question.

**Comment by dannyy3566** [comment]
The ships were in system. We had to delete them manually in the end, nothing else got rid of them.

**Comment by outbools** [comment]
There is a datum reference in starship which didn't cleaned up on qdel

**Comment by Kmsxkuse** [comment]
I noticed something. Pirate ships delete properly but Syndicates are immortal. Can we board pirates?

**Comment by SonixApache** [comment]
This was an issue yesterday, did it get fixed?

**Comment by Qustinnus** [comment]
yes
