### ISSUE TITLE
Slime console does not work

### ISSUE THREAD

**Issue by Chickenmonster1** [FTL13/FTL13#111]
**Problem Description**:
What is the problem?
When trying to use the slime console, I was unable to move the camera, I could drop monkeys on top of the console but not move the camera anywhere else.
**What did you expect to happen**: 
Why do you think this is a bug?
I expected the camera to be able to move and operate like a normal slime control console.
**What happened instead**:
How is what happened different from what you expected?
The camera was stuck in place at the console.
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
It makes slime work difficult
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Use the console near the start of the round.
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by monster860** [comment]
Right, I think I need to change the area used by that console.

**Comment by Qustinnus** [comment]
I'm pretty sure it uses some kind of area defined as virology lab, (Which can be upgraded with cerulean slimes I think)

**Comment by Qustinnus** [comment]
@monster860  easily fixed my ass its been 3 months u jabrony :^)
