### ISSUE TITLE
Bluespace Memes with glasses

### ISSUE THREAD

**Issue by MASMC** [FTL13/FTL13#1122]
[Note]: # (Please enter the commit hash and active testmerge numbers from the "Show Server Revision" verb if you can. If you believe the issue to be caused by a testmerge, please report it in its relative PR thread. State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

It is possible to put glasses and stuff on under hardsuit helmets while they are up. Not too bad of an issue, not gamebreaking.  I can't get server revision as there was an update since the last, but I know it hasn't been fixed in this newest. To reproduce:
1. Grab any kind of eye gear
2. Get hardsuit
3. Wear hardsuit, putting helmet up
4. Put on the eye gear, and watch as your friends are amazed by this bluespace magic!

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

**Comment by ike709** [comment]
I'm 80% sure this is intentional, because I know for a fact being able to put on eyewear under plasmamen helmets is intentional.

**Comment by Altangy** [comment]
This is part of /tg/. They don't have it as an issue because it isn't one
