### ISSUE TITLE
Bridge viewscreen doesn't work, doesn't open at all.

### ISSUE THREAD

**Issue by fizzle7** [FTL13/FTL13#1128]

**Comment by ike709** [comment]
I've seen it work on the latest code.

**Comment by fizzle7** [comment]
I keep shift clicking and changing view mode but it doesn't work, since the last update yesterday that is.

**Comment by MASMC** [comment]
It didn't work for me either, as a borgie.

**Comment by Dahlgaard** [comment]
There are multiple problems here.
The viewscreen itself has setup issues, and the viewscreen controller code is borked and was never intended for more than one viewscreen. Both viewscreen controllers end up linking to the viewscreen on the battlebridge. I've got a fix incoming for these things.

**Comment by FalcoGer** [comment]
I can open the viewscreen window with right click + examine, but it doesn't work with shift clicking.

**Comment by Dahlgaard** [comment]
@FalcoGer  I had experiencing the same as you report. The problems stems from the fact that the object has an "Initialize()" proc, which is supposed to call it's base proc, but fails to do so. Failing to do this ultimately means that a property on the object called "initialized" is never set, and when this isn't the case at a very low level in click.dm the click action is rejected early, and never sent through to other functions that are supposed to handle it. The PR i just posted fixes it, and takes care of some other issues i encountered while debugging this.

**Comment by extramrdo** [comment]
Was this why the viewscreen was always "Almost falling apart!"
