### ISSUE TITLE
Virology Virus Storage

### ISSUE THREAD

**Issue by julsruls** [FTL13/FTL13#1138]
The virus storage is literally empty,  there are no virus samples, no plasma or synaptizine.  This is probably an oversight but makes virology useless except for a virus outbreak. Please add the appropriate items to the virus storage in virology.

**Comment by julsruls** [comment]
actually, none of the storages are stocked

**Comment by MASMC** [comment]
Aetherwhisp tag needed. Mapping issue, from what I know.

**Comment by Kmsxkuse** [comment]
Fixed in #1389
