### ISSUE TITLE
Xenobiology Console Cameras Bug

### ISSUE THREAD

**Issue by julsruls** [FTL13/FTL13#1139]
[Note]: # (Please enter the commit hash and active testmerge numbers from the "Show Server Revision" verb if you can. If you believe the issue to be caused by a testmerge, please report it in its relative PR thread. State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))
Server revision compiled on: 2017-06-18

0a4ef4

Current Infomational Settings:

Protect Authority Roles From Traitor: 0

Protect Assistant Role From Traitor: 0

Enforce Human Authority: 0

Allow Latejoin Antagonists: 1

Enforce Continuous Rounds: 9 of 19 roundtypes

Allow Midround Antagonists: 6 of 19 roundtypes

Whats wrong
The consoles in xenobiology will act up when the ship enters FTL and will make tiles on the cameras appear blocked/invisible when they are actually just covered by the static from tiles that cant be seen.
this can be fixed between jumps or become much worse

**Comment by MASMC** [comment]
Known issue.

**Comment by MASMC** [comment]
It is related to the AI camera bug.
