### ISSUE TITLE
AI Law Ordering

### ISSUE THREAD

**Issue by MASMC** [FTL13/FTL13#1145]
[Note]: # (Please enter the commit hash and active testmerge numbers from the "Show Server Revision" verb if you can. If you believe the issue to be caused by a testmerge, please report it in its relative PR thread. State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

Server revision compiled on: 2017-06-18

0a4ef4

Current Infomational Settings:

Protect Authority Roles From Traitor: 0

Protect Assistant Role From Traitor: 0

Enforce Human Authority: 0

Allow Latejoin Antagonists: 1

Enforce Continuous Rounds: 9 of 19 roundtypes

Allow Midround Antagonists: 6 of 19 roundtypes

It's not only the badminnery, I swear. Because I checked without the panel. I just examined the AI as observer. https://gyazo.com/69ee4b18e3993e4b5c3507db4a6d5704

What is happening here, is that an ion storm had /just/ happened. I check the laws, just to see what it was, and I see this. The ion law is showing as number two, instead, pushing laws one and two up one slot in priority. The AI will /never/ allow anyone to come into harm, while ignoring the rest. So, that's a slight issue.

To reproduce:
1. AI is needed, get yoself one
2. ION storm (BWOINK)
3. Check laws, either by admin verb or examining
4. Cry that AI will not not allow crew to come to harm

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.) This bug was created /without/ the usage of badmin powers, I just looked on the "Show AI Laws" verb, then examined to make sure it was not the verb malfunctioning.

**Comment by Kmsxkuse** [comment]
I cant reproduce this bug.

There is a chance that an ion storm might rearrange the AI laws so that's what might have happened.

I say working as intended.

**Comment by Dahlgaard** [comment]
Agreed with Kmsxkuse, i've not been able to reproduce this either. In my test laws got added as intended.  And as Kmsxkuse writes, the code for the ion storm event contains an execution path that based on probability chances can add an ion law first, and then reshuffle existing ones. 

Concur with working as intended!

**Comment by MASMC** [comment]
Hm. Kek. It's happened more than once, but not recently, could have been a merged PR. Working as intended now, I guess? Closing the issue.
