### ISSUE TITLE
Bug Report : No request console at the bridge

### ISSUE THREAD

**Issue by Superhats** [FTL13/FTL13#118]
**Problem Description**:
What is the problem?
There are no request console on the bridge
**What did you expect to happen**: 
Why do you think this is a bug?
There is supposed to be one at all the important location
**What happened instead**:
How is what happened different from what you expected?
No console was found
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Request consoles at areas like to bridge can be used to make announcements.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Walk to the bridge, not see the console.
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Qustinnus** [comment]
A lot of areas lack one, in my experience.

**Comment by CrAzYPiLoT-SS13** [comment]
I'm going to make a desk subtype so we can fit one in bridge.
