### ISSUE TITLE
Munitions officer needs Earmuffs with radio capabilities 

### ISSUE THREAD

**Issue by Ecolli** [FTL13/FTL13#124]
**Problem Description**:
What is the problem?

**What did you expect to happen**: 
Why do you think this is a bug?

**What happened instead**:
How is what happened different from what you expected?

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Vivalas** [comment]
He has a bowman headset which is literally earmuffs with headset capabilities. Since earmuffs are snowflaked into mobcode horribly and earmuffs are identical to bowman headsets with the exception of bowmans not making you deaf, there is no easy way to implement this and no reason to either.

**Comment by Ecolli** [comment]
i had actually heard you say we needed this a while back, just thought it was forgotten. glad its implemented.  

    On Sunday, August 14, 2016 9:29 PM, Vivalas <notifications@github.com> wrote:
 

 He has a bowman headset which is literally earmuffs with headset capabilities. Since earmuffs are snowflaked into mobcode horribly and earmuffs are identical to bowman headsets with the exception of bowmans not making you deaf, there is no easy way to implement this and no reason to either.—

**Comment by CrAzYPiLoT-SS13** [comment]
This is first on my to-do list when I get back from my vacation.

**Comment by Vivalas** [comment]
The problem is you would need to snowflake it to make bowmans not block it, otherwise it become redundant because bowmans are better.
