### ISSUE TITLE
Conveyor in MO's office controls wrong conveyor or add switches for both. 

### ISSUE THREAD

**Issue by Ecolli** [FTL13/FTL13#125]
**Problem Description**:
What is the problem?

**What did you expect to happen**: 
Why do you think this is a bug?

**What happened instead**:
How is what happened different from what you expected?

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Vivalas** [comment]
I uh, can't reproduce this. Seems to work fine for me.

**Comment by Ecolli** [comment]
it controls "top" conveyor but not "bottom" (from within the office).
 

    On Sunday, August 14, 2016 9:27 PM, Vivalas <notifications@github.com> wrote:
 

 I uh, can't reproduce this. Seems to work fine for me.—

**Comment by CrAzYPiLoT-SS13** [comment]
Just checked variables and they seem fine. Feel free to reopen if it happens again
