### ISSUE TITLE
Space transit glitch

### ISSUE THREAD

**Issue by Superhats** [FTL13/FTL13#126]
**Problem Description**:
What is the problem?
You can fly around the ship while it is in transit
**What did you expect to happen**: 
I expected to be ejected
Why do you think this is a bug?
This isn't supposed to happen
**What happened instead**:
I could freely roam around the ship, like if it was at a stop
How is what happened different from what you expected?
You're supposed to be sent to another Z-level
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
It's a huge glitch
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Wait for the ship to be in transit, go EVA
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
The ship was in transit towards another system

**Comment by monster860** [comment]
The issue here is that you aren't ejected when you cross the shield barrier, which you shouldn't even be able to do.

**Comment by Superhats** [comment]
Once you go far enough behind the shield, the transit animation just stops

**Comment by monster860** [comment]
This is a very big problem, because this bug allows access to areas players shouldn't access, such as the ERT area.
