### ISSUE TITLE
lost connection as AI after FTL jump

### ISSUE THREAD

**Issue by Ecolli** [FTL13/FTL13#127]
**Problem Description**: cant interact with certain devices after FTL jump. says "Unable to establish a connection: You're too far away from the station!"

**What did you expect to happen**: 
Why do you think this is a bug?

**What happened instead**:
How is what happened different from what you expected?

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by CrAzYPiLoT-SS13** [comment]
Can you specify exactly which devices? We already fixed consoles.

**Comment by Ecolli** [comment]
About 19 min into this video you will see me, as the AI, trying to use certain consoles and they don't seem to be working.  Space Station 13 | FTL13 | A Round to remember |
  
|  
|   
|   
|   |    |

   |

  |
|  
|    |  
Space Station 13 | FTL13 | A Round to remember |
 Go check out! http://ftl13.com/phpBB3/ Want to run some Ops with -3C-? Click the link below and join us! Everyon...  |   |

  |

  |

 
 

    On Wednesday, September 28, 2016 10:13 AM, CrAzYPiLoT-SS13 <notifications@github.com> wrote:
 

 Can you specify exactly which devices? We already fixed consoles.—

**Comment by CrAzYPiLoT-SS13** [comment]
Pretty sure this is fixed, reopen if not.
