### ISSUE TITLE
Ship can crash into space ruins.

### ISSUE THREAD

**Issue by Vivalas** [FTL13/FTL13#13]
Mapping issue. ftl_start probably has to be moved somewhere else.

![image](https://cloud.githubusercontent.com/assets/6334647/17075216/1cab0aee-5052-11e6-9784-9c57f5913d44.png)

**Comment by monster860** [comment]
You crashed into a space ruin.....

**Comment by CrAzYPiLoT-SS13** [comment]
My latest commit probably fixed this. Still, if it happens again, reopen this.
