### ISSUE TITLE
Missing APC for Laser cannon. 

### ISSUE THREAD

**Issue by Ecolli** [FTL13/FTL13#132]
**Problem Description**:
What is the problem?

**What did you expect to happen**: 
Why do you think this is a bug?

**What happened instead**:
How is what happened different from what you expected?

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Vivalas** [comment]
Wut? The cannon draws directly from the grid, doesn't need an APC.

**Comment by Ecolli** [comment]
might want to change that...needed to power it down today, had to shut down outgoing power and fire off remaining energy in phaser to then do repairs.  

    On Sunday, August 14, 2016 9:26 PM, Vivalas <notifications@github.com> wrote:
 

 Wut? The cannon draws directly from the grid, doesn't need an APC.—

**Comment by CrAzYPiLoT-SS13** [comment]
And this was exactly why I implemented breaker boxes.

*sigh*
