### ISSUE TITLE
Marooned while on emergency shuttle

### ISSUE THREAD

**Issue by Chickenmonster1** [FTL13/FTL13#133]
**Problem Description**:
What is the problem?
The end game text states we were marooned even though we escaped on the shuttle
**What did you expect to happen**: 
Why do you think this is a bug?
it should state that I escaped the station
**What happened instead**:
How is what happened different from what you expected?
Surviving the trip on the shuttle should count as escaping
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
It could mess with greentexts (if we do that variety)
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Be on the shuttle when it lands on the escape area
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by CrAzYPiLoT-SS13** [comment]
Probably caused by the fact that we do not have a CC z-level anymore. We should probably strip out any references to CC from the code.
