### ISSUE TITLE
Random Radiation Source in Bridge Hallway Aetherwhisp

### ISSUE THREAD

**Issue by Kmsxkuse** [FTL13/FTL13#1333]
Just between the Vault and Teleporter Room, there is this random radiation source of roughly 20ish, 30ish rads pulses.

It's not the Grav Gen, it's something in space.

**Comment by MASMC** [comment]
It is the self destruct, it is fixed in the referenced PR.
Right now, I'd say have an admin delete it.

**Comment by ninjanomnom** [comment]
Fixed
