### ISSUE TITLE
HOS/Sec (along with other jobs) should have better access

### ISSUE THREAD

**Issue by Chickenmonster1** [FTL13/FTL13#134]
**Problem Description**:
What is the problem?
Sec lacks access to the space airlocks closest to the command area, and access to quite a few maintenance tunnels.  Also jobs should have access to maintenance tunnels that directly link to their department (at least the ones that connect straight to it, not the hallway ones).
**What did you expect to happen**: 
Why do you think this is a bug?
Not a bug
**What happened instead**:
How is what happened different from what you expected?
HOS should have at least basic access to the maintenance tunnels and access to anywhere in space for your crime fighting shenanigans.  This also makes it difficult to protect one's self from radiation events.
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Sec/HOS should have as much access as an assistant and radiation can be quite detrimental if it is a very high dosage.  If there is no way for someone to access at least the tunnels of their department, it could be quite painful.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Qustinnus** [comment]
The radiation event thing is an issue for everyone, fyi. captain should just unlock maintenance in a situation like that instead.

**Comment by Chickenmonster1** [comment]
Sorry about the wording on that, the second sentence was meant to refer to all jobs, not just sec.  The idea is that the maintenance door that is directly connected to the department should be accessible to those that work in that department. They don't get main hall access or any extra doors that aren't directly attached to their department.

While just having it be up to the captain sounds like a good idea in theory, as it currently stands captains tend to act like standard SS13 captains in that if they aren't currently flying/protecting the ship they're wandering around, which when the radiation event occurs, will cause them to just go for the tunnels and not activate the all access option.

Some tunnel access is also the standard for traitorous activities too.  When we eventually bring them back, having at least one way into a single tunnel is good to have to make the rounds a bit easier for traitors/make them less likely to be forced to murder people if they walk around their own department.  

But in summary, I don't want all tunnel access for everyone, just each department having access to the door directly attached to their department and sec being able to do their job of snooping around/chasing the graytide through the rat maze.

**Comment by Vivalas** [comment]
I played as HoS today and felt like I had almost all access. Except for botany. For some reason I could access maint and most of all departments but no botany.

**Comment by Qustinnus** [comment]
EVA at phase cannon was also locked as HoS.
