### ISSUE TITLE
Shield-breaking asteroids

### ISSUE THREAD

**Issue by Signmark** [FTL13/FTL13#139]
**Problem Description**:
![image](https://cloud.githubusercontent.com/assets/19763675/17830919/98898f9c-66f4-11e6-8db1-51d980643a36.png)

Well-p accidentaly we went into this location with asteroids. Shields turfs just got replaced by asteroid sand.

However, this doesn't affected shield functionality, but you can left or enter the ship from this breach

**Comment by Signmark** [comment]
![image](https://cloud.githubusercontent.com/assets/19763675/17831315/7398cb3a-66fe-11e6-8eb8-52e04d566a1a.png)
and when we jumped into transit we took that piece with us...

**Comment by CrAzYPiLoT-SS13** [comment]
@monster860
Are these space ruins? If yes, your solution doesn't work. The area thing I
did will most surely stop them from loading in the landing areas, if that's
the case.

**Comment by monster860** [comment]
No, I intentionally placed a thing close so mining can see it out their window
