### ISSUE TITLE
Computer terminals dont have any computer parts on start

### ISSUE THREAD

**Issue by Shuffl3** [FTL13/FTL13#1401]
Yeah, theyre all empty. 

They work once all the parts are in them, so I suppose its a mapping issue. 

Didnt start happening until an update or two ago

**Comment by Kmsxkuse** [comment]
Fixed in #1395

**Comment by Dahlgaard** [comment]
hmm if this was fixed in #1395 that should have been in over the course of the weekend right?
I'm pretty sure i had modular consoles which were partless during rounds over the course of the weekend. Can someone test this ?

**Comment by Koekiegast** [comment]
can confirm that a lot of tablets, laptops, the console in cargo and in engineering maint start without parts
