### ISSUE TITLE
CMO Lost EVA Access

### ISSUE THREAD

**Issue by Kmsxkuse** [FTL13/FTL13#1420]
Since the rebase, CMO lost eva permissions.

I have no idea if this is intentional.

**Comment by Nickthemoonwolf** [comment]
Heads in general seem to have also  lost access to the front of the shuttle, despite still being able to authorize.

**Comment by crossedfall** [comment]
Checked on the maps: Aetherwhisp, Scarab (No EVA), Feliciana, and the Ineese and I confirmed all heads have proper rights to EVA and the shuttle command area.
