### ISSUE TITLE
[Suggestion] Two changes that I feel would improve things tons.

### ISSUE THREAD

**Issue by Fevix** [FTL13/FTL13#1423]
A few improvements I'd like to see: 
1) Decrease the amount of plasma available to the ship at round start
2) Increase the # of average plasma containers available at stations

This would have a twofold improvement to the server: First, Cargo would have an immediate spike in necessity and usage (Currently Cargo is very rarely used, simply because there's no NEED to stop to salvage ships, or to stop at stations for supplies, but needing to stop and buy plasma canisters would force Cargo to be used)
In turn, because Cargo will need funds to purchase these plasma canisters, Science may see a spike in activity as Cargo requests expensive items to be produced for sale. AFAIK, currently Science's only job is "Upgrade Medbay's equipment and repair cyborgs" but this suggestion would give both Cargo and Science more value to the ship as a whole.

Additionally, having to stop and pick up plasma from various stations would extend the length of the rounds, allowing for players to actually play and forcing Captains/Helms/XO's to get out of this "LETS SPEEDRUN EVERYTHING AND WIN FAST GO GO GO GO GO!" mindset.

**Comment by ike709** [comment]
>putting suggestions on github

50% of the reason we have forums is for suggestions

**Comment by Kmsxkuse** [comment]
Wait, if that's one of the reasons, what is the other?

Wait, we have a forum?

**Comment by Fevix** [comment]
The "two" are already listed: 
1: Cargo and Science seeing more usage/requirement
2: Rounds taking more time, allowing/forcing people to actually DO stuff rather than sit around and wait for the Bridge to FTL all around the galaxy then return home.

**Comment by ninjanomnom** [comment]
woops I missed this one, github isnt for suggestions

**Comment by ike709** [comment]
@Kmsxkuse The other reason is ban appeals.
