### ISSUE TITLE
The Power Monitoring Console

### ISSUE THREAD

**Issue by checkraisefold** [FTL13/FTL13#147]
**Problem Description**:
What is the problem?

When opening the power monitoring console in the bridge as a cyborg, all it does is make a big black window open up taking almost your whole screen and stays for a minute or two.

**What did you expect to happen**: 
Why do you think this is a bug?

I expected it to show up with all power usage for the ship.

**What happened instead**:
How is what happened different from what you expected?

Empty, big black box that was un-closable came up and stayed for a minute or so, until it magically disappeared a minute later or so. Further testing proves that an admin probably did something to make it go away, as ecolli was there at the time I did it firstly, then the second time he was still there but I didnt say a word about it and it never went away.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

This can make not knowing players click it and then have to contact a admin somehow to get rid of this big black box. If they don't know what it is, it can ruin their whole round.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

!ONLY TESTED ON CYBORGS!
1) Be a cyborg.
2) Go to bridge.
3) Click on power monitoring console.
4) Done.

**Comment by checkraisefold** [comment]
was this fixed yet?

**Comment by yashaldie** [comment]
seems to be working fine for me
![image](https://cloud.githubusercontent.com/assets/6030362/19710512/f288ffb4-9afc-11e6-9407-4f3ad651b6c6.png)
probably just a tgui issue on client's side. recommend clearing cache and relogging when and if it happens

**Comment by Vivalas** [comment]
@checkraisefold Please make another issue if it is still a problem for you.
