### ISSUE TITLE
Mac is anti-oil

### ISSUE THREAD

**Issue by Koekiegast** [FTL13/FTL13#1501]
[Server revision compiled on: 2017-07-07
4fd701
Current Infomational Settings:
Protect Authority Roles From Traitor: 0
Protect Assistant Role From Traitor: 0
Enforce Human Authority: 0
Allow Latejoin Antagonists: 1
Enforce Continuous Rounds: 9 of 19 roundtypes
Allow Midround Antagonists: 6 of 19 roundtypes

So the mac does not accept oil anymore, not by bottle, not by beaker and it also does not show how much oil it has. I've not yet seen it getting jammed but i haven't operated it long enough for that.
This was at round start and mid-game so before and after ftl.

**Comment by Trugath** [comment]
fixed in #2175
