### ISSUE TITLE
Inflatable wall/doors don't all fit back into the container.

### ISSUE THREAD

**Issue by FalcoGer** [FTL13/FTL13#1535]
As engineer you start with a coffer of inflatable walls and doors. You can also acquire such objects in vending machines and the like.
Once you take some out of it, you can not put all of them back inside. The deflated walls and doors do fit, but the container can only hold so many.
Please increase the size of the container or decrease the size of the walls/doors.

**Comment by AuroranAI** [comment]
Not an issue: Just take out the pen and folder and it all fits back in.
