### ISSUE TITLE
Jumping not working

### ISSUE THREAD

**Issue by coolsurf6** [FTL13/FTL13#16]
**Problem Description**:
When jumping, instead of charging to jump it will immediately jump and when at the destination you can't change as it is stuck at full charge saying it can't jump.

**What did you expect to happen**: 
I expected the ship to charge up then jump and when done go back to the map with an empty charge meter.

**What happened instead**:
Instant jump and when you reach the destination it will lock you as it is 'still charging' but it's full of energy.

**Why is this bad/What are the consequences:**
It locks you from jumping anywhere else forcing you to hard restart to happen again.

**Steps to reproduce the problem**:
Go Captain and head to the Navigational Controller and select a location to jump. When at the destination try to jump somewhere else but it won't do anything.

![image](https://cloud.githubusercontent.com/assets/16472329/17133480/8899aab6-5369-11e6-8146-ad8dbfdcdcb0.png)

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: That's pretty much it.

**Comment by CrAzYPiLoT-SS13** [comment]
There is a canister of plasma in engineering, next to the FTL drive, that needs to be wrenched down in order for the FTL core to charge plasma. Not a bug.

**Comment by Vivalas** [comment]
Yeah on your screenshot it literally says Plasma: 0. I thought this was a bug too.
