### ISSUE TITLE
Nav console improvement (make all tabs always visible)

### ISSUE THREAD

**Issue by FalcoGer** [FTL13/FTL13#1636]
When opening the navigation console you get greeted with ship info, planet map, map (starmap) or planet info.
When switching to ship info, you get the option to go to the planet map or map. but when on the star map, you can't go to the planet map, for example.
Since it always takes 1-3 seconds to switch tabs, it would be nice if you could switch from any tab to any other tab instead of doing all that over 1 to 2 corners, and maybe get lost on the way due to the unintuitive name of the starmap, which should be called starmap rather than just map.

**Comment by ike709** [comment]
You expect someone to touch TGUI?

**Comment by ninjanomnom** [comment]
issues are not for suggestions
