### ISSUE TITLE
ADMIN LOG: Error Spam (took 1.1 seconds to delete).

### ISSUE THREAD

**Issue by Ecolli** [FTL13/FTL13#1667]
ADMIN LOG: Error: /atom/movable/lighting_object([0x2004239]) took longer than 1 second to delete (took 1.1 seconds to delete).

ADMIN LOG: Error: /atom/movable/lighting_object([0x20041d3]) took longer than 1 second to delete (took 1.1 seconds to delete).

ADMIN LOG: Error: /atom/movable/lighting_object([0x200e967]) took longer than 1 second to delete (took 1.1 seconds to delete).

ADMIN LOG: Error: /atom/movable/lighting_object([0x200e966]) took longer than 1 second to delete (took 1.1 seconds to delete).

This is almost unplayable with this popping every 2 seconds for entire rounds.

**Comment by ninjanomnom** [comment]
someone needs to check that this isnt cause by the turf after move proc calling update on the lighting object

**Comment by AuroranAI** [comment]
Duplicate of #1666
