### ISSUE TITLE
Second phaser vanished on FTL jump

### ISSUE THREAD

**Issue by ike709** [FTL13/FTL13#1682]
![image](https://user-images.githubusercontent.com/5714543/28496134-1f11f9e0-6f29-11e7-8482-78ce6352bb1f.png)
Plating, wiring, and gun all vanished when we jumped.

**Comment by ninjanomnom** [comment]
check for runtimes but I doubt that's the issue here

probably the stationary dock is misconfigured but until someone wants to figure out the base cause it wouldn't be a bad idea to make the gun's beforeShuttleMove return true

**Comment by ninjanomnom** [comment]
Fixed in the recent shuttle cleanup
