### ISSUE TITLE
Crew Monitoring console is broken

### ISSUE THREAD

**Issue by Alkheemist** [FTL13/FTL13#169]
The crew monitoring console currently does not work. I am informed that this is a known issue by Nickvr628 (TrialAdmin)

**What did you expect to happen**: 
Crew monitoring should probably:
Show a map

**What happened instead**:
Map does not appear

**Why is this bad/What are the consequences:**
Currently not very unusable

**Steps to reproduce the problem**:
Open crew monitoring console

![crewmonitoring](https://cloud.githubusercontent.com/assets/7487313/18809753/aaa5b982-82c7-11e6-9e14-3c4326f80fcf.png)

**Comment by TalkingCactus** [comment]
This is caused by a config setting which disallows the minimap subsystem to run as it's very expensive. TG has a fix for it being expensive, though it's only a one time thing per map(only station Z level (1)).
See here for the config option: https://github.com/FTL13/FTL13/blob/master/config/config.txt#L260
If it's already on then it's likely a more complex problem.

**Comment by CrAzYPiLoT-SS13** [comment]
Yes, that is the exact reason. I will be leaving this issue up for documentation though.

**Comment by Shadowlight213** [comment]
Hello! I'm the guy who refactored the minimap caching system on tg.
While yes, the system I did assumes the station to only be on one zlevel, it shouldn't be too hard to rework it to function with your system.
I'll take a shot at porting it when I get the chance.

**Comment by CrAzYPiLoT-SS13** [comment]
There's no issue with the system, it works perfectly, I tested it. We are
still keeping it disabled for performance reasons, until we have a public
release. Thanks for pitching in, though.

**Comment by Shadowlight213** [comment]
@CrAzYPiLoT-SS13
My caching system was specifically created to deal with the performance issues.
It makes it so the generation only needs to be run if you want to update the map. It also added fallback maps that can just be hard coded in case there's no updated data map.
It's hard to explain, but essentially it makes it still display a map from storage even if generating(which is the expensive part) is off.
