### ISSUE TITLE
missing icons

### ISSUE THREAD

**Issue by Koekiegast** [FTL13/FTL13#1697]
This monday, round that ended around 14:49 amt.

The icons for the clown duffle bag and the gilded horn in the hud are missing. edit: this was before jump and undock.

**Comment by stobarico** [comment]
I'd also like to add that there are some other things missing icons, they are:
- Captain's Fountain Pen
- Glockenspiel
- Achordeon
There may be more iconless instruments that i do not remember

**Comment by Maciekkub** [comment]
I'd also like to point out, that the icon of "Space law" (It's a book) does not show up

**Comment by Koekiegast** [comment]
also the engineering duffle bag and the captain's duffle bag don't show up on your back, probably other ones too

**Comment by stobarico** [comment]
#1925

**Comment by stobarico** [comment]
## **Fixes missing icons**
#1925

**Comment by Koekiegast** [comment]
you missed the clown duffle bag, and there are a lot of dufflebags that are not visible on your back

**Comment by stobarico** [comment]
Like i said, i wasn't able to fix duffelbags, but now i might know what's causing the problem

**Comment by Koekiegast** [comment]
i missed you saying that then, woops
