### ISSUE TITLE
Ruins and shipwrecks can block phase cannon shots

### ISSUE THREAD

**Issue by Altangy** [FTL13/FTL13#1751]
To recreate, shoot down a few ships until one of them spawns in front of the phase cannon and then attempt to kill another ship. The shots will never hit ships because the laser is blocked.

**Comment by Koekiegast** [comment]
and it can destroy the turfs that would make the shots do their thing

**Comment by ninjanomnom** [comment]
Should be fixed with the recent shuttle cleanup
