### ISSUE TITLE
Duplicate type path /datum/component

### ISSUE THREAD

**Issue by ninjanomnom** [FTL13/FTL13#1752]
Ship components use the same type path as the new datum components from #1607 , ship components need to be renamed.

No bugs seem to have resulted from this yet but it's only a matter of time, not to mention this is probably causing performance drag.

Yeah I fucked up when merging that.

**Comment by monster860** [comment]
I guess we should rename our ship components to /datum/ship_component?

**Comment by outbools** [comment]
refactor them to use DCS >:^)

**Comment by ninjanomnom** [comment]
This is quite possibly the source of some of the most recent lag. Maybe even the crashing problems.
