### ISSUE TITLE
atmos slower than a fat man on a scooter

### ISSUE THREAD

**Issue by Koekiegast** [FTL13/FTL13#1843]
Round id: 273

sometimes at roundstart atmos is just broken, meaning for instance cans empty themselves into the pipes very slowly and the teg acts a bit wierd and canns fill up slowly also move trough pipes slowly, just general slownes edit: it apears in this case to have sped up quit a bit into the round, well after power goes out tough

**Comment by TMTIME** [comment]
fixed with a lag nerf
atmos differences on planets was the source
