### ISSUE TITLE
Ship to Ship combat is broken

### ISSUE THREAD

**Issue by Altangy** [FTL13/FTL13#1849]
We can't shoot them. They can't shoot us. This runtime might be related 
[20:14:11] Runtime in ship.dm, line 92: Cannot read null.type proc name: generate ship (/datum/starship/proc/generate_ship)
src: pirate space rock \"Atmosiamin... (/datum/starship/asteroid)
call stack:
pirate space rock \"Atmosiamin... (/datum/starship/asteroid): generate ship()
pirate space rock \"Atmosiamin... (/datum/starship/asteroid): New(0)
Ships (/datum/controller/subsystem/ship): init datums()
Ships (/datum/controller/subsystem/ship): Initialize(8518)
Master (/datum/controller/master): Initialize(10, 0)

**Comment by Vivalas** [comment]
I don't know what the issue is but that runtime definitely isn't related.
