### ISSUE TITLE
Magic pipe vision

### ISSUE THREAD

**Issue by Koekiegast** [FTL13/FTL13#1872]
Round id: 287 when we entered FTL travel and i had my t-ray scanner mode on on my engineering goggles the pipes and wires i was seeing permanently were fully visible on the tiles but not interactable they did disapear after a bit tough

**Comment by MrMaclang** [comment]
Not a bug. That is how t-rays work

**Comment by Koekiegast** [comment]
i know how t-ray works but it was probably FTL lag because normaly they aren't fully visible and permanently visible even if you move acros the room
