### ISSUE TITLE
Bots are Unable to patrol the station

### ISSUE THREAD

**Issue by mirrorfagic** [FTL13/FTL13#188]
**Problem Description**:
When You attempt to Put a bot into patrol mode, It simply will disengage patrol mode around right after being put into patrol mode 

**What did you expect to happen**: 
I think this is a bug cause your bots are supposed to be able to patrol the station.

**What happened instead**:
The bots simply just Disabled patrol mode right after being put into it

**Why is this bad/What are the consequences:**
It makes making Bots completely useless. 

**Steps to reproduce the problem**:
Step 1: Build a Robot (not a borg)
Step 2: Put it into patrol mode.
Step 3: It will put it's self out of patrol mode for no reason.
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I do not know what else to tell you, I was just simply building bots as a Roboticist.

**Comment by AdamElTablawy** [comment]
Did nobody place navigators in the map?

**Comment by CrAzYPiLoT-SS13** [comment]
Nope. This is a known issue.

**Comment by ninjanomnom** [comment]
probably fixed, new shuttle code new bugs
