### ISSUE TITLE
Modular computers are fucked

### ISSUE THREAD

**Issue by JStheguy** [FTL13/FTL13#1944]
For some odd reason every single laptop, tablet, and modular console on the ship spawn with no components inside. I would write this off as intended, but there are loads of these things scattered around public spaces, and many of the empty laptops sport the description "A low-end laptop often used for personal recreation.", which only shows up for a specific type of preset laptop that starts with some components and software pre-installed, going by the actual code.

**Comment by Cdey78** [comment]
Has been known forever, nobody has decided to try and fix it for a bit though.

**Comment by Qustinnus** [comment]
Cdey noone cares if "it was known forever" because there was no issue for it on github.  Now there is. If you knew this was an issue then why havnt you made an issue yourself?
