### ISSUE TITLE
Reinforced Wall get repaired when jumping in or out of FTL

### ISSUE THREAD

**Issue by Night007** [FTL13/FTL13#195]
**Problem Description**:
When jumping in and out of FTL Space (changing Z-Level with the "Ship") a partilally deconstructed reinforced wall gets repaired.

**What did you expect to happen**: 
The parameter of the reinforced wall, how much it is deconstructed, should be transfared to the new Z-Level. So that it should have the same level of deconstruction/destruction it has before the "jump".

**What happened instead**:
The reinforced wall gets fully "repaired" when jumping (changing Z-Level).

**Why is this bad/What are the consequences:**
It takes some time to deconstruct a reinforced wall. When the ship decides to jump, your work is ruined and you have to start over again.

**Steps to reproduce the problem**:
1. Take a wirecutter and partilally deconstruct a reinforced wall.
2 (optional). Deconstruct it further with the neccesary tools.
3. Jump somewhere with the navigation controls.
4. Get back to the wall to see that it is repaired/reseted.

[When reaching the reinfored wall grid, your "progress" is saved]

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing else.

**Comment by ninjanomnom** [comment]
probably fixed, new shuttle code new bugs
