### ISSUE TITLE
Whenever the lasers are fired, the enemy ship absorbs it and extends the shields BEYOND the max capacity.

### ISSUE THREAD

**Issue by Hollexian** [FTL13/FTL13#20]
**Problem Description**
*What is the problem?* Look at title

**What did you expect to happen**: 
*Why do you think this is a bug?* Because everyone and their mom thinks that, and I believe the developers would not have the intent to make it impossibly difficult to take down a ship.

**What happened instead**
*How is what happened different from what you expected?* I expected the shield percentages to come down, then we would fire the torpedoes, then we could have a happy-go-lucky time looting the shit out of the syndies.

**Why is this bad/What are the consequences:**
*Why do you think this is an important issue?* Because you can't even destroy the ship you're after, and also it leads to the point where you cannot escape the ship (that's a whole different bug though)

**Steps to reproduce the problem**:
*The most important section. Review everything you did leading up to causing the issue.*

We jumped planet to planet, star system to star system trying to reach syndie territory, the torpedoes were pre-loaded, though, and then we fire the lasers onto the ship's shield, it gets stronger, and then we're fucked.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: *Anything else you can tell us.* The gamemode was extended, and also hallucinations were happening, and I GUESS there was a lighting glitch whenever the ship went to FTL speed and whenever it stopped.

also I know that the devs know but they told me to report it ;(

**Comment by CrAzYPiLoT-SS13** [comment]
@Vivalas Just in case

**Comment by Vivalas** [comment]
#19

**Comment by monster860** [comment]
@Vivalas You still need to fix running awaqy?

**Comment by Vivalas** [comment]
I'm going to PR that along with some other bugs I found tomorrow. This bug is fixed though.
