### ISSUE TITLE
Ship Tactical Console unable to switch subsystem targeting

### ISSUE THREAD

**Issue by Altangy** [FTL13/FTL13#2016]
Attempting to use the Ship Tactical Console as a human mob or an Aghost with A.I. interact does not appear to allow people to change subsystem targets.

**Comment by Wulfestwulf** [comment]
This.... This seems like a hard as FUCK thing to do...

**Comment by Altangy** [comment]
I thought this issue was closed? I'm going to do that considering I'm almost 100% @TMTIME fixed this
