### ISSUE TITLE
Nav console window has visual issues with outdated Internet Explorer, and on No Frills mode

### ISSUE THREAD

**Issue by EvilJackCarver** [FTL13/FTL13#205]
**Problem Description**:
Nav console, and others, have issues displaying when Internet Explorer is outdated, or when it is on No Frills mode. This issue is not localised to the FTL-13 server, however greatly affects it due to how console-intensive bridge command positions are.

When IE is outdated, the nav console tends to take upward of a minute to open and can crash the game. The FTL map shows squares instead of circles on the star map, and I was having severe difficulty using the helm.

This was on a fresh Windows 7 Ultimate install, so I believe it was IE8 that was installed. The issue was corrected by installing IE 11.

**System environment**
BYOND build 510, Windows 7 Ultimate, build 7601, x64
EVGA GTX 970 SSC / AMD FX-8350.

For further system environment, see attached .NFO.

[sysinfo_dot-NFO_file.zip](https://github.com/FTL13/FTL13/files/532260/sysinfo_dot-NFO_file.zip)

**Comment by Vivalas** [comment]
Yell at BYOND for using the shittiest interface design ever, until then, not much we can do until someone makes a better UI system for SS13.

**Comment by Surrealistik** [comment]
The lag generated by the Sleeper, NAV, Door Hacking and Power Management console have been pretty unbearable at IE8 or on No Frills. Really hoping there's a way to mitigate the problem somehow and get rid of these incompatibilities/issues. Was an unpleasant surprise coming over from CM to find that so many interfaces cause unbearable lag.

**Comment by Vivalas** [comment]
I prefer plaintext / fancy tg html as well but the starmap wouldn't be possible without it. Most of the other inferfaces probably would be without the bells and whistles, but most of those were converted from html to tgui and going backwards would take a lot of work.
