### ISSUE TITLE
Mechbay Power Port not charging mechs

### ISSUE THREAD

**Issue by ShadowCommander** [FTL13/FTL13#207]
**Problem Description**:
The Mech Recharge Station doesn't always recharge mechs, because the computer doesn't recognize that a mech is on the pad. 

It's possible to fix the problem temporarily by deconstructing the Mechbay Power Port and unscrewing and rescrewing in the monitor, then resyncing the montor the the Mechbay Power Port.

**What did you expect to happen**: 
The mechs should always recharge when put on the recharge pad.

**What happened instead**:
The mechs sometimes charged and most of the time didn't.

**Why is this bad/What are the consequences:**
Mechs aren't able to be recharged.

**Steps to reproduce the problem**:
1. Build a mech
2. Use up some of the charge
3. Drive the mech onto the charging pad
4. It might start charging

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I think the problem is caused by the ship taking off or landing, and that the Mechbay Power Port only works when landed or in transit depending on which it was synced on.

**Comment by jblack144** [comment]
I can confirm this is an issue. To fix it, simply take apart and reassemble the power port. and reconnect the console to the power port. It magically works again.
