### ISSUE TITLE
Upgraded power cells are lower in capacity than regular power cells (in borgs)

### ISSUE THREAD

**Issue by Gouty** [FTL13/FTL13#210]
**Problem Description**:
Upgraded power cells are lower in capacity than regular power cells (in borgs)
Regular Cell - 7500
High Capacity - 1250
Super Capacity - 1500

(the rest are untested)

**What did you expect to happen**: 
I expected that when a robo placed in a high capacity to have a higher capacity (normally 15000 for high cap, 20000 for super cap and 30000 for hyper)

**What happened instead**:
I had a lower capacity

**Why is this bad/What are the consequences:**
Because using these cells I cannot function for very long as a borg

**Steps to reproduce the problem**:
Replace the cell of a borg

**Comment by yashaldie** [comment]
should be good to close this one now.
