### ISSUE TITLE
Crazy Planet Overwriting

### ISSUE THREAD

**Issue by Gouty** [FTL13/FTL13#214]
**Problem Description**:
If you remain on planet 1 when the ship takes off, and the ship visits planet 2, then planet 2's features appear around the players on planet 1 (i.e. planets are on 1 z-level)

**What did you expect to happen**: 
I kind of expected it to happen due to engine limitations, but from a gameplay perspective I would expect each individual planet to have its own z-level or to overwrite the existing planet in a way that is immersive for the players still on planet 1.

**What happened instead**:
New rocks appeared all around me

**Why is this bad/What are the consequences:**
My immurshuns

**Steps to reproduce the problem**:
Land on a planet, stay on planet while ship leaves, remain on planet while ship lands on another planet

**Possibly related stuff**:
Perhaps this should be part of a bigger discussion about what should happen to people left on a planet, should they have a simple means to get back to the ship? (which reminds me, I probably ought to try the jaunter next week)  Should they be killed in freak lava eruptions after a set period of time?

**Comment by monster860** [comment]
Did it also delete you?

**Comment by Gouty** [comment]
No, me and one other player survived and boarded the ship.  We just saw new rocks appear from left to right.  I'm not sure if existing rocks were removed in places also (so there might be an issue with planets essentially being added together)
