### ISSUE TITLE
Null gas mixtures

### ISSUE THREAD

**Issue by Bit1000** [FTL13/FTL13#2156]
I've been getting this error every tick in Dream Daemon, and it lasts for the entire round.
The longer the shift goes, the more lag it seems to generate.

> Runtime in unsorted.dm,1207: /datum/pipeline has one or more null gas mixtures, which may cause bugs. Null mixtures will not be considered in reconcile_air().

![tickerror](https://user-images.githubusercontent.com/31507640/29951644-37ae54ea-8e81-11e7-8a52-be3b4a32c738.png)

**Comment by Wulfestwulf** [comment]
Ah... this is a mapping issue half because the atmos system is a bit borked but if that was to be turned into a non-null gas through Coding magic I would think it would be fixed and maybe fix alot of the lag.
