### ISSUE TITLE
"Jump to Area" results in doom

### ISSUE THREAD

**Issue by Bit1000** [FTL13/FTL13#2164]
Using the admin command, "Jump to Area" and selecting "Engineering" will sometimes teleport you to the middle of empty space in a completely different z-level. This happens even before the ship jumps, at round-start.

![jump to area dead](https://user-images.githubusercontent.com/31507640/29950915-5d5a4a82-8e7c-11e7-901d-370d3b7efe94.png)

**Comment by Altangy** [comment]
This one should be solved based on time's shuttle pr.
