### ISSUE TITLE
SM needs a emergency "Flush" room button

### ISSUE THREAD

**Issue by Ecolli** [FTL13/FTL13#230]
Need external doors to SM room to have a button so we can open it and flush out the gas within the room.

**Comment by AdamElTablawy** [comment]
I don't see how this is possible, or a good idea. You'd open the doors and engie would flood.

I can see about adding syphons to the SM room that can be toggled, or perhaps blast doors with grilles behind them to allow gas drain while letting the SM stay, but.

**Comment by CrAzYPiLoT-SS13** [comment]
Uh, why is the SM not an anchored structure?

**Comment by Qustinnus** [comment]
@AdamElTablawy I'm not sure if I'm misunderstanding you, but what Ecolli means is that the blast door to the west of the SM would open and the gas could drain, I'm not sure if this would pull the shard however.

**Comment by monster860** [comment]
The shard is incapable of being pulled by airflow. I coded it that way.

**Comment by TatsumakiMagi** [comment]
Can't you just press the eject button without pressing the button that activates the mass ejector?

If I remember rightly that just opens the doors and all the gas gets sucked out.

**Comment by SonixApache** [comment]
In-round issue. You could just build ~4 scrubbers that vent into space, and switch them on through the air alarm when needed.

**Comment by Vivalas** [comment]
Really outdated, multiple maps and now pretty sure all of them can be flushed.
