### ISSUE TITLE
Need to add "Solars crate" to the trade station order system.

### ISSUE THREAD

**Issue by Ecolli** [FTL13/FTL13#231]

**Comment by Qustinnus** [comment]
thanks @Ecolli you know what a man wants

**Comment by Ecolli** [comment]
Its definitely time. We need a back up plan for power.  

    On Sunday, October 30, 2016 6:57 AM, Qustinnus <notifications@github.com> wrote:
 

 thanks @Ecolli you know what a man wants—

**Comment by monster860** [comment]
https://github.com/FTL13/FTL13/blob/master/code/modules/cargo/packs.dm#L564

What are you talking about?
