### ISSUE TITLE
Add a "Colonization Kit" - A kit that has all the basics for kickstarting a planetside colony

### ISSUE THREAD

**Issue by Qustinnus** [FTL13/FTL13#237]
Title, I'm not a 100% what this would require but I'd say a lot of fairly easy to set up machinery required to make a habitable colony.  Perhaps solars would be good but I have heard that they don't work on planets(bug?).

We'd definitely need some boards and materials for basic machinery though, for example for small size oxygen machinery etc.

I also think this kit should be locked and need a code just like the nuke, which would prevent players from looting the kit for its contents without reason as it would probably contain quite some items.

 Also gives us a ton of opportunity to name it something alike the "G.E.C.K." in fallout.

**Comment by Hollexian** [comment]
I agree, however, maybe not have this able to be accessed on the ship, maybe on a supply drop (assigned as a ruin the admins can spawn) sent by centcomm to help the colonists colonize.

**Comment by AdamElTablawy** [comment]
done
