### ISSUE TITLE
Borg name does not count

### ISSUE THREAD

**Issue by Sagrotter** [FTL13/FTL13#243]
When you start a round as borg and you set your name in lobby, game does not give you the name you've chosen, it's gives you "Default Borg-[number]"

It should take your name from lobby right?

The borg is already not good "class" to play, low power is a real issue, and this default name is just annoying.

That would be nice if I'm not named "Default Borg", I realy like playing borg

See you next round (y)

**Comment by Vivalas** [comment]
'Nother /tg/ related bug.

**Comment by ninjanomnom** [comment]
Not a bug, monster didn't enable borg names in config.
