### ISSUE TITLE
Once killed as a blob, 're-enter corpse' re-enters you into blob mode with no way to re-ghost

### ISSUE THREAD

**Issue by EvilJackCarver** [FTL13/FTL13#246]
**Problem Description**:
When you hit 're-enter corpse' as a blob, you are stuck in the blob view with no way to exit. This could be coded to prevent blobs from suiciding because they didn't want to play.

**What did you expect to happen**:
(I accidentally pressed it, it wasn't intentional.)

**What happened instead**:
It brought me back into blob mode, with no way to exit. The connection dropped and I was able to join as spectator.

**Why is this bad/What are the consequences:**
Users who accidentally press it may be stuck and unable to spectate the round or respawn.
![ftl13_alpha_testing_nsv_astraeus_2016-11-06_17-45-05](https://cloud.githubusercontent.com/assets/1784490/20042996/0f05103c-a44a-11e6-975e-ed2cdec01395.png)

**Steps to reproduce the problem**:
I was made blob by @Qustinnus as a 'round's fucked let's make it more so' thing, and died. I went to go orbit the SM to check on it, missed, and clicked 're-enter corpse' by mistake. I was put back into the blob mode, and couldn't type `ghost` or `suicide` to re-enter ghost mode.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I was made blob near dorms/EVA.

**Comment by Vivalas** [comment]
This should probably go to /tg/ was well, if not already, they might even have a fix.
