### ISSUE TITLE
gas flilter cant flilter out plasma 

### ISSUE THREAD

**Issue by PaznerIV** [FTL13/FTL13#2508]
Round ID:442
So yeah the gas filters cant seem to filter out the plasma that the SM produces it can filter out CO2, O2 or any other gas but not plasma.

**Comment by AuroranAI** [comment]
sounds like the bug pubby fixed with filters just breaking loops; fixed upstream(?)

**Comment by praisenarsie** [comment]
@pubby

**Comment by pubby** [comment]
I took a quick look and didn't see anything obvious as to why plasma wouldn't be filtered out.

Dunno.

**Comment by PaznerIV** [comment]
It was an odd bug and one of the admins online fixed it some how so maybe ask them what was wrong with it

**Comment by crossedfall** [comment]
Unable to reproduce this, most current engine builds filter our plasma. This may have been caused by atmos lag which was fixed with our FTL rework.

**Comment by Altangy** [comment]
I have been on and off trying to recreate this for about 9 months now. Even in play I've never seen this happen
