### ISSUE TITLE
Wrecks cause issues with shields

### ISSUE THREAD

**Issue by Ecolli** [FTL13/FTL13#252]
wreckage shield generators cause a bug to "overlaps" shields on the ship (cannot turn off shields to allow people in/out)

possible issues with FTL drive as well, not confirmed though. 

Suggest editing all wrecks to spawn NONE working equipment.

**Comment by Qustinnus** [comment]
Not a bug, it's a mapper's fault. If you put working equipment made for the main ship it'll do it's job for the main ship.

**Comment by Ecolli** [comment]
Monster requested I make this an issue. He intends to fix it. 

    On Wednesday, November 16, 2016 4:55 PM, Qustinnus <notifications@github.com> wrote:
 

 Not a bug, it's a mapper's fault. If you put working equipment made for the main ship it'll do it's job for the main ship.—
