### ISSUE TITLE
[Scarab] Latejoin observe issues

### ISSUE THREAD

**Issue by ike709** [FTL13/FTL13#2525]
I observed on the scarab after a round had started and I spawned in the middle of nowhere.

![](https://t.gyazo.com/teams/nomemeshere/6c0a82f79e1e43cadb0016baca851f44.png)

![](https://t.gyazo.com/teams/nomemeshere/2cf60ff6fc8706e061505748a0003550.png)

**Comment by ninjanomnom** [comment]
Put issues with testmerges in the testmerge pr
