### ISSUE TITLE
Enemy Ship

### ISSUE THREAD

**Issue by RemBestFurry** [FTL13/FTL13#2536]
[Note]: I was expanding ship, from the arrivals outside the Windows to a 5 away tile-lattice zone when suddenly a ship appears on the zone and we're near me and the CE, we decided to go in to loot but then admin played "bad idea" in my mind and after 1-2 minutes, the ship that looked like wrecked and half built loaded and crushed on me, gibbing me instantly. .

**Comment by Qustinnus** [comment]
admin played "bad idea"


remember that when an admin says bad idea, it's probably not a good idea.

**Comment by Altangy** [comment]
That admin was me. I've only been reminding players that salvage is broken every round.
