### ISSUE TITLE
Power Monitor in my tablet

### ISSUE THREAD

**Issue by RemBestFurry** [FTL13/FTL13#2537]
[Note]: In the engineer Tablet, when you download power monitor, it doesn't work. it doesn't a ppear, a red message appears in the chat and that's all.

**Comment by Cdey78** [comment]
Not a bug, the power monitor is incompatible with mobile devices.

The way it works is if there's a wire node under said console with said power monitoring function, it measures the power flowing through that.
Mobile devices cannot connect to said wires.
