### ISSUE TITLE
Viro's APC without external power conection (Mapping problem)

### ISSUE THREAD

**Issue by JonanBH** [FTL13/FTL13#255]
**Problem Description**:
The APC power cable is turned to the wrong side, this way the APC isn't connected to the ship power lines

**What did you expect to happen**: 
Isn't a "bug", it's a mapping error , fast solution, the APC should be connected on the power supply.

**Comment by elbrad0** [comment]
I noticed this a while back - as an engineer I was able to wire the APC back into the grid but it involved removing pipes and a disposal unit.
