### ISSUE TITLE
Make supply crates obj/

### ISSUE THREAD

**Issue by Qustinnus** [FTL13/FTL13#257]
**Problem Description**:
Supply crates are currently only available through the supply console, I want to be able to simply spawn them in on the map / through scripts

**What did you expect to happen**: 
bruh

**What happened instead**:
go away

**Why is this bad/What are the consequences:**
I can't finish my loot script

**Steps to reproduce the problem**:
die

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: this format is dumb.

**Comment by CrAzYPiLoT-SS13** [comment]
It's not dumb, it's literally needed for it to be like this.

**Comment by Qustinnus** [comment]
screw the system

**Comment by 4chongerino** [comment]
just use call proc and call the proc that spawns in the supply crates???

**Comment by Qustinnus** [comment]
just dont assume non-byond devs know how byond coding works???

**Comment by Vivalas** [comment]
This is retarded.
