### ISSUE TITLE
Midround Atmos Bug

### ISSUE THREAD

**Issue by dannyy3566** [FTL13/FTL13#265]
**Problem Description**:
What is the problem?
Every single round I've played, somewhere between 45 minutes to an hour and a half into the round, the Nitrogen storage in Atmos suddenly vanishes.
**What did you expect to happen**: 
Why do you think this is a bug?
All of the nitrogen in storage up and vanishes, it's not all used, it's not pumped elsewhere, it's just suddenly gone.
**What happened instead**:
How is what happened different from what you expected?
Self Explanatory.
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
80% of the ship's atmos is supposed to be nitrogen, this makes it almost impossible to replace atmosphere after hull breaches.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Start server, set up atmos,  wait 45-90 minutes, see Nitrogen storage empty.
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us. This has happened in a lot of varied situations, and i'm not always looking exactly when it happens, but it has happened directly on planets, in space, in FTL space, in combat, and probably somewhere else as well.

**Comment by Vivalas** [comment]
This is interesting but hard to reproduce or verify, if this does happen during a test game, please notify a staff member so we can see what's happening at the time the nitrogen disappears.

**Comment by Vivalas** [comment]
@dannyy3566 Is this still an issue?

**Comment by dannyy3566** [comment]
@Vivalas It very much is, it's happened quite a number of times since.
