### ISSUE TITLE
Scarab Cargo issues

### ISSUE THREAD

**Issue by Chaemera** [FTL13/FTL13#2660]
Several issues with the Scarab's cargo bay setup.

1. Upon round start the inbound/outbound conveyor does not connect properly with the station, there is a LARGE segment of naked floor between the ship's conveyor and the station's conveyor.
2. Attempting to send packages into the delivery chute by the on-ship conveyor does not work, as the conveyor reverses itself in front of the plastic flaps.
3. There seems to be no way to label destinations for packages for the disposals/delivery system.
4. The Mulebot located in the cargo bay has no destinations other than QM#1.

**Comment by TMTIME** [comment]
1 is due to the ship 'crushing' items under the sheild wall when it moves to that area, including roundstart
2 and 3 there is no delivery system iirc

**Comment by Ecolli** [comment]
1) That is a known bug caused by the code rebase and has something to do with trade stations not loading properly.
2) That's not a delivery chute, it's for MAC rounds only. 
3) Not a delivery chute
4) I'm trying to get help setting up flags on the ship so beepsky and mike not will work 👍

**Comment by Altangy** [comment]
As the ship does not dock anymore, that means the section is not needed anymore
