### ISSUE TITLE
Map rotation chose Aetherwhisp but Scarab was loaded.

### ISSUE THREAD

**Issue by ike709** [FTL13/FTL13#2774]
Aetherwhisp was chosen at round end but during initialization next round Scarab was loaded.

>Map rotation has chosen Aetherwhisp for next round!

>Loading Scarab...

An admin had initiated the reboot if that matters.

>Rebooting World in 1 second. Initiated by LordWalnut.

**Comment by LordWalnut** [comment]
That was me, sorry, I wanted to get more images for the wiki so I rotated to Scarab.
