### ISSUE TITLE
Master at arms's jacket has broken icon

### ISSUE THREAD

**Issue by ike709** [FTL13/FTL13#2775]
The formal one, not the armored one. I don't think it's a mapping issue, but I noticed it in the MAA's locker on the scarab.

**Comment by megaultraninja** [comment]
It's good on Aetherwisp, I'll test on Scarab soon.

**Comment by ike709** [comment]
Notice how I said on the scarab.

**Comment by megaultraninja** [comment]
Notice how you said that you thought it wasn't a mapping issue.
let me compile it for scarab.

**Comment by megaultraninja** [comment]
just checked on Scarab, and you are correct. /obj/item/clothing/suit/security/masteratarms has a borked icon.
