### ISSUE TITLE
[Scarab] FOB shuttle destroys ship airlocks upon returning to the ship

### ISSUE THREAD

**Issue by TMTIME** [FTL13/FTL13#2797]
Sorta a known bug, as its the same issue as the ship destroying cargo belts when docking to a station.

![dreamseeker_2017-10-07_00-31-36](https://user-images.githubusercontent.com/29457447/31310048-d98431c6-ab88-11e7-9f56-d8ced1ba0072.jpg)
Image of a freshly returned shuttle, with three airlocks, three tiny fans and the shuttle console deleted

This situation is slightly more of a problem due to the tiny fans under the airlock getting deleted

**Comment by ike709** [comment]
I wonder why this doesn't happen on the aetherwhisp.

**Comment by Wulfestwulf** [comment]
@Ecolli

**Comment by Ecolli** [comment]
@Wulfestwulf something to do with the areas glitching out. not sure if its a mapping error or coding error. I'm leaning towards the later

**Comment by Wulfestwulf** [comment]
@Ecolli Well atherwhisp does not seem to have this issue... Maybe for a quick fix for now just move the console to another tile.

**Comment by Altangy** [comment]
It is mapping thing, had the same issue on the Feliciana. You can't embed the docking port in the shuttle area as the shuttle will "occupy"that area as well. It's an easy mapping fix.
