### ISSUE TITLE
Xeno airlock cycle on Scarab Glitch

### ISSUE THREAD

**Issue by jblack144** [FTL13/FTL13#2829]
To replicate: have two people. place one on an open door, and the other to start the cycle. The doors do nothing and the buttons won't work after the failed cycle. Happened on both the exterior airlock to the pods and to RnD.

**Comment by Ecolli** [comment]
Are both people trying to cycle the doors at the same time?

**Comment by jblack144** [comment]
No, this should be able to be done with a monkey too. Put a monkey where the opened airlock is and try to cycle it.

**Comment by Ecolli** [comment]
O are you saying it won't cycle if someone is standing in the doorway? Probably like that for safety reasons so they don't get crushed.

**Comment by jblack144** [comment]
Yes, but then remove the monkey and try to cycle again. It won't cycle, even if it should be able to.

**Comment by jblack144** [comment]
Okay, I just cloned the project and setup a quick test server. 

Went to the airlock that goes from RnD to Xeno on Scarab. Cycled the airlock so that the southern airlock is open. Placed a monkey in the way of the airlock, then press the cycle button for the northern airlock. Nothing happens. Makes sense! Don't want to crush the monkey.

Put the monkey off of the airlock. Push button. Still nothing. The xeno lab access console which allows you to manually cycle doesn't do anything either.

I'm able to replicate this everytime.

**Comment by Wulfestwulf** [comment]
Again... TG issue... same happens with the Viro airlocks. Its because it locks up and its not that big of a issue. So... TG issue... I seem to find a pattern with most of these issues...
