### ISSUE TITLE
Xeno's camera glitches to show nothing after a jump

### ISSUE THREAD

**Issue by jblack144** [FTL13/FTL13#2831]
Round ID: 535
Map: Scarab
How to replicate: FTL jump while using the camera. It's not a consistent bug, and it does fix itself eventually, though it may be 30 minutes or so, which makes xeno's job alot harder.

**Comment by LordWalnut** [comment]
Yeah, we know about this. Thanks for the report!

**Comment by TMTIME** [comment]
fixed with a lag nerf

**Comment by Altangy** [comment]
@Vivalas This can be closed as it was fixed a long time ago with TMTIME's lag fix in which the ship no longer moves z-levels
