### ISSUE TITLE
Option to turn off parrallax

### ISSUE THREAD

**Issue by Qustinnus** [FTL13/FTL13#285]
**Problem Description**:
I got the hardware graphics turned off because I have hybrid cards (I own a laptop thus I have both a integrated and GTX 1060 dedi). If I have it turned off, space is white. If I turn it on, my entire screen is white.

**What did you expect to happen**: 
Seriously this is such a fucking redundant question,

I expected nothing to happen, obviously. It's supposed to work. why the /hell/ is this a question

**What happened instead**:
Literaly what the problem description said. redundant question

**Why is this bad/What are the consequences:**
screen is white, space is white. If I wanted white stains on my screen I'd go play citadel

**Steps to reproduce the problem**:
1. buy 1500 euro laptop for high quality UE4 work and gaming
2. be unable to play 2d spess game on shitty engine from 2001 or something
3.cry at monster

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Okay, no WGW here, alright?

**Comment by AndySok** [comment]
>I'd go play citadel

*clap* *clap* *clap*

**Comment by Vivalas** [comment]
@monster860 Please.
