### ISSUE TITLE
New Consoles do not maintain their facing when repaired

### ISSUE THREAD

**Issue by MinimallyViable** [FTL13/FTL13#2950]
[Note]: # (<B>Please enter the `Round ID` from the `Status` panel if you can!</B> If you believe the issue to be caused by a testmerge, please report it in its relative PR thread. State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

Scenario: Xo consoles were damaged on Aetherwhisp. Used screwdriver, added glass, used screwdriver. After this, the consoles were facing south instead of facing east/west as they were originally.

**Comment by RemBestWaifu** [comment]
This happens too when they are made, at least, when I do them.
Everytime I made a console it faced west

**Comment by TMTIME** [comment]
Stob fixed this

**Comment by crossedfall** [comment]
Specifically fixed in #3541
