### ISSUE TITLE
Mining shuttle still lands on tendrils/chasms

### ISSUE THREAD

**Issue by MinimallyViable** [FTL13/FTL13#2951]
[Note]: # (<B>Please enter the `Round ID` from the `Status` panel if you can!</B> If you believe the issue to be caused by a testmerge, please report it in its relative PR thread. State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))

[Admins]: # (If you are reporting a bug that occured AFTER you used varedit/admin buttons to alter an object out of normal operating conditions, please verify that you can re-create the bug without the varedit usage/admin buttons before reporting the issue.)

I only observed this : Miners reported landing on a chasm.

**Comment by TMTIME** [comment]
Ike fixed it ages ago
