### ISSUE TITLE
Drone static vision with sprites

### ISSUE THREAD

**Issue by RemBestWaifu** [FTL13/FTL13#2982]
[Note]: When a player enters a drone shell, all other living entities are shown as a static, the problem is, that the mob (_any mob_) shown in the static is only shown alive (_this does not count humans or monkeys, because they "fall" when dead_) for example, in the static vision you can see a carp moving its tail, but upon examining it, it's dead with a different sprite (_dead version_) this can happen to any mob.

Here you have some images in gyazo:
**Carp in FOB**: https://gyazo.com/2eb02e16095d7d43ea58c3a7db576e42
**Carp in Medbay**: https://gyazo.com/f19bf54813c2eaf412005ae5481da65c

**Comment by ike709** [comment]
Almost certainly a TG bug.

**Comment by praisenarsie** [comment]
i can confirm this is a tg bug because static vision is a higgs-bugson
