### ISSUE TITLE
Cameras when you jump

### ISSUE THREAD

**Issue by Dr0ppy** [FTL13/FTL13#30]
**Problem Description**:
What is the problem?
As an AI when you jump the camera feed breaks
**What did you expect to happen**: 
Why do you think this is a bug?
It shouldnt do that
**What happened instead**:
How is what happened different from what you expected?
Static
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Makes life as AI hard
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Jump the ship, be AI
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Relogging fixes it

**Comment by Vivalas** [comment]
Everything goes to static?

**Comment by Dr0ppy** [comment]
yup

**Comment by monster860** [comment]
I've tracked down the cause of the problem!

ChangeTurf doesn't retain the camerachunk obscured images, or lighting overlays (#35)
