### ISSUE TITLE
engineering scanner goggles meson problem

### ISSUE THREAD

**Issue by Koekiegast** [FTL13/FTL13#3000]
Round id: 566
Whenever you have some engineering scanner goggles and you put those in tray mode (or it breaks and switches to tray) and then back to meson the vision breaks slightly as everything apears to be light and not darkened like it should when you can't see the tile or it's too dark.

**Comment by RemBestWaifu** [comment]
That happens in certain sectors.

**Comment by Wulfestwulf** [comment]
/TG/ issue, blame /TG/ because of this.
