### ISSUE TITLE
warping into planet orbit and then out kills ship

### ISSUE THREAD

**Issue by 4chongerino** [FTL13/FTL13#303]
**Problem Description**:
warping out of a planet kills every /turf instance thus destroying the ship

**What did you expect to happen**: 
safely warp out

**What happened instead**:
it killed everything

**Why is this bad/What are the consequences:**
everything dies

**Steps to reproduce the problem**:
warp into planet orbit, attempt to warp out, everything dies

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: get this error when we enter planet orbit : ADMIN LOG: dock(): shuttle FTL Ship cannot dock at , error: not_a_docking_port

**Comment by 4chongerino** [comment]
oh also yellow pages object is blank

**Comment by Vivalas** [comment]
These are issues not seen on our official server for some reason.

**Comment by gitgud-software** [comment]
At least 10 people have seen this error occur on a codebase running 1:1 with FTL13, multiple times across 510 and 511.

We are running FTL on a Ubuntu 16.10 GNU/Linux virtual machine.

**Comment by monster860** [comment]
That is really weird, this shouldn't happen.

**Comment by gitgud-software** [comment]
Yeah if you want to see it in action I can temporarily give you coder privs to check out the situation. I'll message you in Discord.

**Comment by monster860** [comment]
The _maps directory is not compiled into the .dmb, it needs to exist.
