### ISSUE TITLE
MAC Cannon construction?

### ISSUE THREAD

**Issue by DerFlammenwerfer** [FTL13/FTL13#307]
**Problem Description**:
To my knowledge, there is no way to rotate the breech or barrel of a MAC when constructing one

**What did you expect to happen**: 
I was hoping the two components would work something like the Phase cannons.

**What happened instead**:
The breech and barrel, upon construction, are always facing south

**Why is this bad/What are the consequences:**
The boards exist for these parts in storage, but if you can't build a new cannon what's the point?

**Steps to reproduce the problem**:
Construct the MAC breech and MAC barrel.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
Extended Roleplay; Trying to rebuild the MAC. Also attempted to use build mode to place them in the correct orientation, but the tactical console would not pick it up. Phase cannons worked fine though.

**Comment by Funce** [comment]
@Vivalas MAC cannons are now constructable.

**Comment by ike709** [comment]
@Vivalas No longer a bug.
