### ISSUE TITLE
Why do you guys have 1200 open Pull Requests

### ISSUE THREAD

**Issue by Bawhoppen** [FTL13/FTL13#3242]
Do you guys need some assistance or something?

**Comment by dannyy3566** [comment]
Mirror bot pulling from TG's codebase and a lack of coders to fix the mirror PRs.. We would welcome another contributor, hah.

**Comment by Bawhoppen** [comment]
You need more than just a contributor to fix this kind of mess...

You need a git expert

**Comment by dannyy3566** [comment]
Nah, we just need a mass of coder bodies to throw at the PRs to get them fixed, as I'm given to believe it's not a complex fix, just a lot of time going over the bits the bot screws up.

**Comment by optimumtact** [comment]
get out of here baw

**Comment by Bawhoppen** [comment]
why are you here

**Comment by Chnkr** [comment]
all of this could've been prevented if you guys would've isolated your changes and additions in a seperate folder like we do at hippie, then you could've just hit merge on all incoming /tg/ pulls, or close them.

**Comment by PJB3005** [comment]
The PR bot system is just fundamentally worthless.

If you merge every PR and put the FTL13 code into its own folder to prevent conflicts, you might as well just not merge the individual PRs and just do large direct merges of the upstream branch using git manually.

If you don't merge every PR and pick and choose, your fork slowly desynchronizes until the point where it becomes unmaintainable, which is probably where FTL13 is at.

What was the advantage of this system exactly?

**Comment by Super3222** [comment]
someone tell RD to blow the bot

**Comment by Bawhoppen** [comment]
Just merge all the ones that don't break and see what happens

Or find a git expert who knows how rebases actually work because god they're weird

**Comment by PJB3005** [comment]
Or stop using rebases and use merges instead because they're not painful.

A rebase just goes and redoes all your commits to be on top of the branch
you're rebasing to.

**Comment by Kmsxkuse** [comment]
Holy shit. I remember when we were down to 5 pages of PRs. Why is it up to 55?

Did no one try to merge PRs when I stopped making Mirror Fixes?

**Comment by Jalleo** [comment]
Appears so.

**Comment by AuroranAI** [comment]
you'd do 1 pr to get 10 more dropped on you, and you'd hit a wall where you needed a maintainer to merge something, which would take a couple days
in that couple days, a stack of prs around the amount you just did appears, ad infinitum

**Comment by Vivalas** [comment]
>What was the advantage of this system exactly?

I guess it fixed lag, but now we basically need another rebase.
