### ISSUE TITLE
CTF batteries bugged

### ISSUE THREAD

**Issue by Superhats** [FTL13/FTL13#328]
**Problem Description**:
What is the problem?
The laser rifles can't be reloaded

**What did you expect to happen**: 
Why do you think this is a bug?
It stops people from playing CTF

**What happened instead**:
How is what happened different from what you expected?
The laser rifle can't be reloaded, which is a bug

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
It's really difficult to play CTF without guns

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Acquire laser rifle
Remove battery
Try to load new one

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
It was CTF

**Comment by Vivalas** [comment]
_HIGH PRIORITY_
