### ISSUE TITLE
Phase cannon faces one way but shoots the other

### ISSUE THREAD

**Issue by Vivalas** [FTL13/FTL13#33]
This is a weird one I noticed today. After you guys upgraded it, the sprite was facing east but the bolts were being shot south. I don't know how to reproduce it or what causes it, just that I believe it was related to being upgraded.

**Comment by Vivalas** [comment]
This will be important after I rework weapons since the bolts won't be leaving the map and thus won't be registering as hits

**Comment by CrAzYPiLoT-SS13** [comment]
I couldn't reproduce. You sure someone didn't rotate it?

**Comment by Vivalas** [comment]
I'm almost certain it was facing east yet shooting south. I'm fine with you closing this until it comes back up (???). I don't even know how this would be possible.

**Comment by CrAzYPiLoT-SS13** [comment]
I literally tried every possible way of reproducing this, no dice. Feel free to reopen it if it happens again.

**Comment by Vivalas** [comment]
Just saying this happened again in a recent test round.

**Comment by monster860** [comment]
I think this bug is fixed with the new cannon sprites.
