### ISSUE TITLE
Air Alarm Remote Control

### ISSUE THREAD

**Issue by DamagedEngine** [FTL13/FTL13#336]
#**Problem Description**:
I would like to have a remote air alarm control computer installed in the atmos room that can access the air alarms on the ship, see their status and change their settings.

**What did you expect to happen**: 
This would make atmos tech MUCH more effective because I would be able to turn off the vents in breached rooms remotely, get to the room, fix it, and open the vents again to pressurize it.

**What happened instead**:
N/A

**Why is this bad/What are the consequences:**
In the current state if the game it's very easy to loose all distro pressure due to vents pumping air into a hull breach since the atmos equipment is pretty small, air supply is limited and the ship gets hit all the time. This would make the ship much easier to maintain and give the gift of breathing to the crew.

**Steps to reproduce the problem**:
N/A

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**
I have seen these atmos control units on some servers, and there may be one in the TG code already. To prevent grieving those code bases only allow remote air alarm control when there is an alarm coming from the controller, otherwise you can only look at the options and no the change them. This would work well for FTL 13 since the main purpose for this feature is to turn off vents in rooms suffering from breaches, which cause red atmos alerts.

**Comment by Nickvr628** [comment]
+100. As an experienced atmos tech this would make our lives so much easier.
