### ISSUE TITLE
Floor Tile Icons

### ISSUE THREAD

**Issue by valzargaming** [FTL13/FTL13#337]
**Problem Description**: 
Prying the tiles that display the station name and replacing them does not use the correct icon. 

**What did you expect to happen**: 
It should place with the tile icon that was there originally.

**What happened instead**:
The default tile icon was placed

**Why is this bad/What are the consequences:**
It's a silly bug with a simple fix.

**Steps to reproduce the problem**:
Crowbar the tile and replace it.

Picture for reference: http://i.imgur.com/jyTFwv4.png

**Comment by valzargaming** [comment]
They're supposed to, unless perhaps the mapper used the default tile and somebody just changed the icon state.

**Comment by Vivalas** [comment]
@valzargaming Is this still an issue?
