### ISSUE TITLE
Medbay does not have sinks!

### ISSUE THREAD

**Issue by valzargaming** [FTL13/FTL13#338]
**Problem Description**:
Medbay does not have any sinks. These are necessary to avoid sepsis and prevent the spread of diseases. It's also basic hygiene!

**What did you expect to happen**: 
Go to medbay and find a sink.

**What did you expect to happen**: 
Go to medbay and find a sink.

**What happened instead**:
I cried because there are no sinks.

**Why is this bad/What are the consequences:**
Spread of disease and lack of hygiene.

**Steps to reproduce the problem**:
Walk into medbay.

**Comment by M11gamer** [comment]
From what I see it has already been solved :)
