### ISSUE TITLE
Engineering does not have a single recharger for power cells.

### ISSUE THREAD

**Issue by valzargaming** [FTL13/FTL13#339]
**Problem Description**:
Engineering does not have any rechargers recharger for power cells.

**What did you expect to happen**: 
Find a recharger in Engineering or Atmospherics.

**What happened instead**:
Cried because I found not find a recharger.

**Why is this bad/What are the consequences:**
There is no way to recharge a power cell without having access to Security.

**Steps to reproduce the problem**:
Try to find a recharger.

**Comment by Vivalas** [comment]
@Ecolli  @monster860

**Comment by M11gamer** [comment]
#460
