### ISSUE TITLE
Access is screwed up across the board.

### ISSUE THREAD

**Issue by Vivalas** [FTL13/FTL13#34]
Based on some of the adminhelps I got and personal experienced, there are some really crazy things happening with access. The boozemat was fixed, but I noticed some others, there may be more

-Kitchen public doors don't open for the CMO
-Security doors don't open for the captain
-HoP desk doesn't open for the captain

There are probably more.

**Comment by monster860** [comment]
Yell at @CrAzYPiLoT-SS13

**Comment by CrAzYPiLoT-SS13** [comment]
Hm, sorry for these, goddamned defines got to my head
