### ISSUE TITLE
The Hidden Booze-o-mat is ID locked to the bartender

### ISSUE THREAD

**Issue by valzargaming** [FTL13/FTL13#340]
**Problem Description**:
The Hidden Booze-o-mat is ID locked to the bartender

**What did you expect to happen**: 
Any old assistant could get completely wasted.

**What happened instead**:
I cried because _Access denied._

**Why is this bad/What are the consequences:**
Spacemen can't get drunk without going to the bar.

**Steps to reproduce the problem**:
Attempt to access god's gifts to spacemen as anyone other than bartender and cry when you can't.

Picture for reference: http://i.imgur.com/TA6bjPz.png

**Comment by Vivalas** [comment]
_HIGH PRIORITY_

**Comment by SonixApache** [comment]
Can't just hack it and disable the IDcheck wire?

**Comment by GeneralGoose** [comment]
theres a booze-o-mat in mining shuttle which miners don't have access to as well

**Comment by AuroranAI** [comment]
@Qustinnus close lie, tuning fork is in the trash

**Comment by Qustinnus** [comment]
they didn't give me my fucking perms yet REEEE
