### ISSUE TITLE
APC in robotics dissappeared when built but not turned on

### ISSUE THREAD

**Issue by GelatinousGlob** [FTL13/FTL13#343]
Robotics got hit by an enemy round and blew up the APC, I placed the frame, wired it, put the board in then screwdrivered it. As soon as the screwdriver finished the APC disappeared completely, it was not in any examine menus, and was not under the wall when I took the wall down. 

The terminal wires still existed but the APC itself was nothing. I couldn't turn the power on and couldn't build a new APC because it said there already was one.

Not sure what the cause was or if it is repeatable.

**Comment by dannyy3566** [comment]
This is a bug caused by the new power revamp removing power cells from APCs, but thank you for documenting it. I will now start poking monster with links to this.

**Comment by Vivalas** [comment]
@monster860 @dannyy3566  @GelatinousGlob Is this still an issue?
