### ISSUE TITLE
FTL Drive doesn't charge if there is too much plasma input

### ISSUE THREAD

**Issue by crossedfall** [FTL13/FTL13#3458]
Round: #378  
Map: Aetherwhisp

If the FTL drive is connected directly to the plasma mains it will break requiring a player to toggle the digital valve off-and-back-on to reset it. Once broken it will need to be reset after every jump before it will charge. 

[Note]: The shield generator does not appear to suffer from the same issue, even if it's connected to the same line.

**Comment by ondrej008** [comment]
I've kind of experimented, and it looks like if there's a continous input of plasma with a Volume Pump set to 1L/s, it just works. I had a volume pump going into the FTL drive set to 1L/s and another to the shield generator, and it just kind of worked.

**Comment by ondrej008** [comment]
Seems to be only if the pipe is full, ie. there is no more plasma going in.

**Comment by ondrej008** [comment]
Apparently it's the valve that's present on some FTL setups, as the valve doesn't transfer the gas for some reason, this can be fixed by simply unwrenching and wrenching the valve and the plasma should flow.
