### ISSUE TITLE
Issues for Trailblazer

### ISSUE THREAD

**Issue by Cw3040** [FTL13/FTL13#347]
**Problem Description**:
I spawned as Cargo Technician, in Atmospherics. There is no lighting in Atmospherics.

**What did you expect to happen**: 
I expected to spawn in the cargo bay, as per normal, and to be able to see without a flashlight.

**What happened instead**:
Neither of these things happened

**Steps to reproduce the problem**:
Change spawns around.

**Comment by Qustinnus** [comment]
@monster860

**Comment by Vivalas** [comment]
@Qustinnus This was fixed right?

**Comment by MrMaclang** [comment]
Do we even use trailbrazer?
