### ISSUE TITLE
Map loader load different areas like one.

### ISSUE THREAD

**Issue by Dennok** [FTL13/FTL13#3471]
On Scarab ship replaces /area/shuttle/ftl/engine/engineering (Enginering (supermatter engine), Port Auxilary SMES, Starboard Auxilary SMES) by one.

**Comment by Vivalas** [comment]
What?

**Comment by Dennok** [comment]
Now ship don't jump like a shuttle, now it wont reply.
But before, it merge different named areas with one type to one area.
On example we have 3 areas named A B C, but it all "area/my_аrea". On load areas B and C merge to A and we have one area A in 3 different places with 3 apc.
Problem in loader, it check only types, not names.

**Comment by Dennok** [comment]
Now areas on Scarab ship fixed.
