### ISSUE TITLE
Engineering has almost no lights

### ISSUE THREAD

**Issue by DamagedEngine** [FTL13/FTL13#348]
**Problem Description**:
Engineering has pretty much no light fixtures

**What did you expect to happen**: 
I expected to see where I am going.

**What happened instead**:
Atmospherics and a nearby hallway are pitch black and don't have any sort of lighting.

**Why is this bad/What are the consequences:**
uh, arent rooms supposed to have lights especially when full of equipment
**Steps to reproduce the problem**:
walk into engineering

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Qustinnus** [comment]
@monster860

**Comment by Vivalas** [comment]
@Qustinnus Fixed right?
