### ISSUE TITLE
Wires don't have power in them.

### ISSUE THREAD

**Issue by T-Wiz** [FTL13/FTL13#349]
**Problem Description**:
Wires, while still providing connections between the APC's and SMES and equipment, do not actually have any power in them.

**What did you expect to happen**: 
Wires should state how much power is in the network when hit with a multitool. People should be shocked when running into grills with a wire node under them.

**What happened instead**:
There is no power in the wires. Grills are unelectrified.

**Why is this bad/What are the consequences:**
Areas are a lot less secure. Engineers cannot tell if there is a break in the network, since all wires report no power when a multitool is used.

**Steps to reproduce the problem**:
Use a multitool on a wire running between an SMES and powered APC.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Tested on two different servers.

**Comment by Qustinnus** [comment]
@monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860

**Comment by Vivalas** [comment]
@monster860 @Qustinnus @T-Wiz Is this still an issue?
