### ISSUE TITLE
CMO's office problem

### ISSUE THREAD

**Issue by JessHorserage** [FTL13/FTL13#350]
**Problem Description**:
What is the problem?
CMO's office isn't accessable by the CMO
**What did you expect to happen**: 
Why do you think this is a bug?
Airlocks could have been rushed over.
**What happened instead**:
How is what happened different from what you expected?
I expected to get in.
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Can't get in without shocking yourself.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
went to office, didn't get in
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Qustinnus** [comment]
@monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860 @monster860

**Comment by Vivalas** [comment]
@Qustinnus This is fixed right?
