### ISSUE TITLE
Can we just fix this already? (Dug sand tiles looking like space)

### ISSUE THREAD

**Issue by Altangy** [FTL13/FTL13#3501]
![image](https://user-images.githubusercontent.com/25562238/37858523-f36a8b36-2edb-11e8-9c41-4e320ae7b828.png)

Just dig any sand.

**Comment by Cdey78** [comment]
I might look at it on Monday

**Comment by Qustinnus** [comment]
sand is missing a _dug iconstate. The space is just the "background"

**Comment by HawkerTheGreat** [comment]
ohhhey thats me!
