### ISSUE TITLE
Cryo area is missing control computer for cryo

### ISSUE THREAD

**Issue by monster860** [FTL13/FTL13#351]
**Problem Description**:
What is the problem? Cryo area on trailblazer doesn't have a control computer

**What did you expect to happen**: 
Why do you think this is a bug? Adminlogs are complaining about it

**What happened instead**:
How is what happened different from what you expected? For there to be a control computer

**Why is this bad/What are the consequences:**
Why do you think this is an important issue? You can't recover items

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Load up trailblazer map.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us. Trailblazer

**Comment by Qustinnus** [comment]
wew the unfinished medbay isn't finished?

what an unexpected twist.
