### ISSUE TITLE
Crowbarring an APC open will cause it to disappear

### ISSUE THREAD

**Issue by SomeguyManperson** [FTL13/FTL13#352]
**Problem Description**:
What is the problem?
When trying to replace a battery in an APC, the sprite disappeared from view after crowbarring it open
**What did you expect to happen**: 
Why do you think this is a bug?
The APC cover would open
**What happened instead**:
How is what happened different from what you expected?
The APC sprite disappeared from view, it still exists and gives power to the room, but you can't interact with it aside from pointing at it
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
You can't replace batteries in an APC
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
open an APC's cover with a crowbar
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us. New Trailblazer map

**Comment by monster860** [comment]
APC's don't even have batteries, we removed them in the power update.

**Comment by CrAzYPiLoT-SS13** [comment]
This is caused, for some reason, by the APCs not properly reading their overlays anymore, even though we didn't touch them for the most part.
