### ISSUE TITLE
Snow broke

### ISSUE THREAD

**Issue by Altangy** [FTL13/FTL13#3542]
Hey look, there is a thing that is broken
![image](https://user-images.githubusercontent.com/25562238/39952861-d647b61a-556d-11e8-9abf-067654221bac.png)
send halp the snow is full of stars
![image](https://user-images.githubusercontent.com/25562238/39952871-0227fbb4-556e-11e8-942b-7741f9993209.png)

**Comment by crossedfall** [comment]
Just to make fixing it a little easier, no actual dug state currently exists. 

![image](https://user-images.githubusercontent.com/26130695/40285765-8cb19aa8-5c65-11e8-9c82-8a2355dcb821.png)

DM file that needs to be updated is https://github.com/FTL13/FTL13/blob/master/icons/turf/floors/planet.dmi

In my admittedly brief search, I wasn't able to find a suitable state that we could rip from one of the other codebases.

**Comment by crossedfall** [comment]
@Cdey78 Is that something you can create? It's basically the same issue as #3501

**Comment by Cdey78** [comment]
A bit late, but I could try.
