### ISSUE TITLE
Attempting to compile the source code through Dream Maker leads to an error

### ISSUE THREAD

**Issue by ModDownloading** [FTL13/FTL13#3573]
After downloading the source and opening ftl13.dmb in Dream Maker, attempting to compile or clean compile results in the output:

loading ftl13.dme
code\game\gamemodes\wizard\soulstone.dm:123:error: expected var or proc name after . operator
ftl13.dmb - 1 error, 0 warnings

I am not sure if there is supposed to be another step involved, but the FTL13 Wiki page https://ftl13.com/wiki/index.php?title=Downloading_the_source_code (under "Hosting a Server") does not seem to include any other steps, and the source code of most other servers I have downloaded seem to compile, so I am inclined to think this is a minor bug with the code.

**Comment by TMTIME** [comment]
You can't compile FTL13 using Byonds beta. Switch to stable and it'll work

**Comment by ModDownloading** [comment]
Ah, that explains it! Thank you for the quick reply, even if I am a bit late at following up on it.
