### ISSUE TITLE
Conveyor power usage too high.

### ISSUE THREAD

**Issue by Metallumere** [FTL13/FTL13#3584]
https://github.com/FTL13/FTL13/blob/master/code/modules/recycling/conveyor2.dm#L107
Based on this line, it seems conveyors should be using 100 power each, however in my testing they seemed to use 1000 each instead. Setting this number to 10 instead of 100 is an easy fix, however this could be a greater issue at work.
Somewhere an extra zero is being added. If any other machines suffer from this issue, I have not noticed. Will update this if I find more.

**Comment by Qustinnus** [comment]
im fairly sure thats intended. theres a modifier that changes the rate of power use.

**Comment by Metallumere** [comment]
Well good to know it's not broken. Should that number be reduced to something more reasonable then? Seems very excessive for a simple conveyor.

**Comment by Altangy** [comment]
I'd say if anything this is a consistency issue. Very few things use as much power as a conveyor
