### ISSUE TITLE
Mac guns have a chance to blow up on the crew.

### ISSUE THREAD

**Issue by Altangy** [FTL13/FTL13#3599]
Aerwhisp and I were just minding our own business watching the round as spoopy ghosts when the crew fired the mac cannon and it blew up in the bay. We've have reports of this before and considering I've now seen it, this is an actual issue I can put up.

**Comment by TMTIME** [comment]
https://github.com/FTL13/FTL13/blob/master/code/game/machinery/mac_cannon.dm
line 67 and 84-85 implies this is a feature for a poorly maintained MAC cannon

**Comment by Vivalas** [comment]
Yes, letting the MAC cannon drop to 0% accuracy makes it blow up on the next shot.

**Comment by Vivalas** [comment]
Unless this can get reproduced in another fashion.
