### ISSUE TITLE
FTL Drive resets genetic powers/disabilities

### ISSUE THREAD

**Issue by jackattack414** [FTL13/FTL13#3605]
Round #: 1044
Issue: FTL vs Genetics
Details: FTL jumps seem to reset genetic powers/disabilities in player characters, possibly in all humanoids, except those in containers unless I am mistaken. Side note: no text indicates that you have lost said powers/defects.
Steps to recreate bug: Give yourself [via injector] a genetic power/disability, then take an FTL jump. Most noticeable with impaired eyesight and similar disabilities

**Comment by jackattack414** [comment]
injector

**Comment by crossedfall** [comment]
Injectors do not permanently give you powers. They only last for a few minutes at best. To quote [our wiki](https://ftl13.com/wiki/index.php?title=Guide_to_genetics#How_Mutations_Work):

> Remember that this applies only to mutating via scanner: injectors always manifest powers, if their block is above C00, but are temporary.

**Comment by Vivalas** [comment]
Will close without further testing.

**Comment by crossedfall** [comment]
@Vivalas Except you didn't...

**Comment by Vivalas** [comment]
Wanna fite mate
