### ISSUE TITLE
"1 in stock," but infinite stocks

### ISSUE THREAD

**Issue by extramrdo** [FTL13/FTL13#3649]
[Note]: #1495

Get mission to acquire volatile bomb. Go to cargo station.  Press button to order volatile bomb for 0 credits. Checkout. Crate appears on appropriate pad. Move crate. Press button to order volatile bomb.
Expected result: Console says "No more bombs left in stock!"
Observed result: Console adds a bomb to the cart.

Push button to order another volatile bomb.
Expected result: Console says "No more bombs left in stock!" because cart contains 1 bomb already.
Observed result: 2 bombs in the cart.

Checkout.
Expected result: No bombs appear, since one has been purchased.
Observed result: 2 more bombs in crates appear.

The problem is "Only 1 in stock" etc. does not actually apply ever, to any item. The in-stock counter doesn't decrement when buying or adding to cart, nor is it ever enforced.

_Rest in peace, Dave the Accountant._

**Comment by MASMC** [comment]
Sorry, I've had a lot to do recently!
- Dave, the Inter and totally not slave to the Gods
