### ISSUE TITLE
Duffelbags are broken, and have been broken, FOR TWO YEARS!!

### ISSUE THREAD

**Issue by SgtxRootbeer** [FTL13/FTL13#3658]
so
in lines 331 and 332 in 
code/game/objects/items/weapons/storage/backpack.dm 
refers to duffelbags icon and item states as "duffle"
this is ok since storage.dmi also has the icon named "duffle"
but fails when you go to:
icons/mob/back.dmi
the issue being that someone didn't check the spelling and the icons are named "duffel"

the real ironic part is that the DMI was changed, in a way that broke it, because our bot mirrored a pr from /tg/.
the /tg/ pr was made to fix an issue
an issue that I MYSELF REPORTED
![image](https://user-images.githubusercontent.com/22112255/51446246-464b0480-1cc4-11e9-9356-7246ed2b023f.png)

**Comment by crossedfall** [comment]
Fixed by #3661
