### ISSUE TITLE
ClothesMate empties when BREP'd

### ISSUE THREAD

**Issue by extramrdo** [FTL13/FTL13#3659]
[Note]: #1593

Interact with ClothesMate. (AutoDrobe? It's just name variants of the same machine). Observe that there are a number of clothes in there, each with 1 in stock. Wield BRPED. From a distance, use BREPD on ClothesMate. Observe the text describing the parts: three ClothesMate stocking containers. Open-hand interact with the ClothesMate again.
Expected: The clothes are still there.
Observed: Every item has 0 stock.

Disassemble the clothesmate (screwdriver, crowbar). Observe that the Clothesmate board and three Clothesmate stocking containers fall out of the machine frame. Examine the stocking containers.
Expected: A description, and maybe text saying they're full
Observed: A description, and the next line says it is empty.

**Comment by covertcorvid** [comment]
This issue is the same with all vending machines.
