### ISSUE TITLE
Signing up as a Curator at round start sometimes does not place you correctly.

### ISSUE THREAD

**Issue by GoatMonarch** [FTL13/FTL13#3669]
Issue: Signing up as a Curator does to give you the correct spawn point at times.

Cause: It is likely due to the job spawn is still labeled "Librarian" instead of "Curator" on most ships.

Personal note: I believe this issue is a mapping issue, and should be easily solved by relabeling the librarian spawnpoints to the new job name. HONK!

Edit: It'd seem like most of our maps just copy paste the Aetherwhisp's spawn points. Meaning if any mapper used that map's librarian spawnpoints likely suffers from this issue.

**Comment by crossedfall** [comment]
Do you know which maps are actually effected? Or at least which maps you've seen it on?

**Comment by GoatMonarch** [comment]
> Do you know which maps are actually effected? Or at least which maps you've seen it on?

It's definetively affect on the following: Aehterwhisp, Butterfly, Feliciana. I'll make a listing shortly.

**Comment by GoatMonarch** [comment]
Listing goes as: Aetherwhisp, Butterfly, Feliciana, Ineese, Scarab, SpaceSHIP (Central hallway), and lastly the Yacht.

Of course the Trailblazer and FOB are not really covered by this issue, considering Trailblazer is incomplete, and the FOB merely has a bunch of assistant spawns all over so it's a non issue.

**Comment by crossedfall** [comment]
So, every map has this issue? Hrm. Welp. Time to summon the mapper gang

@Altangy @IndusRobot @NIXC

**Comment by crossedfall** [comment]
Assigning Goat since they noted they'd fix the maps in discord.

**Comment by GoatMonarch** [comment]
The fix has been merged. Closing issue.
