### ISSUE TITLE
Mac Cannon disappears after use.

### ISSUE THREAD

**Issue by Hollexian** [FTL13/FTL13#368]
**Problem Description**:
What is the problem?
title
**What did you expect to happen**: 
Why do you think this is a bug?
i don't think it disappearing is intended
**What happened instead**:
How is what happened different from what you expected?
i expected it to be visible like always
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
people cant see it
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
use it and it'll probably disappear
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
nawwwwwww

**Comment by CrAzYPiLoT-SS13** [comment]
Dupe.
