### ISSUE TITLE
Phase Cannons on Salvage ships bug out

### ISSUE THREAD

**Issue by Stealthkibbler** [FTL13/FTL13#381]
When you go to salvage a cannon off an enemy ship it will bug out if it does not have plating under it.

Example: I try to remove a phase cannon from an enemy wreck, I can't so I then have to build plating under it. wrench it and then unwrench it, it can now be moved.

**Comment by Qustinnus** [comment]
shitty mapping @Nickvr628

**Comment by ninjanomnom** [comment]
We no longer have phase cannons on salvage maps
