### ISSUE TITLE
Captain needs to be able to view the weapons screen AND Nav map

### ISSUE THREAD

**Issue by Stealthkibbler** [FTL13/FTL13#382]
The captain shouldn't have to get off his comfy chair and walk over and breath all over the weapons officer or helms officer just to see what's going on, he should be able to view the weapons screen and nav screen from the comfort of his chair. It's important for the captain to know this information when trying to decide on whether they should jump or not.

**Comment by Qustinnus** [comment]
I agree, but he shouldn't be able to actually do anything like fire or warp.
