### ISSUE TITLE
Link robotics/cloning consules.

### ISSUE THREAD

**Issue by Ecolli** [FTL13/FTL13#39]
**Problem Description**:
Robotics and medical consoles are not connected properly. Also robotics is missing a "brain" holder for borging.

**What did you expect to happen**: 
Why do you think this is a bug?

**What happened instead**:
How is what happened different from what you expected?

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by CrAzYPiLoT-SS13** [comment]
Actually, this was only partly fixed, cloning still needs to be connected

**Comment by CrAzYPiLoT-SS13** [comment]
Actually, fully fixed
