### ISSUE TITLE
No ID console in Bridge or Captains Office

### ISSUE THREAD

**Issue by Stealthkibbler** [FTL13/FTL13#390]
When you have multiple people asking for multiple different access it leads to hops tiny box of an office being crowded as fuck and annoys and frustrates the HoP, if the captain wants to give out special access to Bridge officers or other command staff he should be able to in his office or the bridge.

**Comment by Qustinnus** [comment]
it's the poor sods only task at the moment :^)

**Comment by Stealthkibbler** [comment]
HoP can lead salvage teams and actually do his job that is ensuring the civlians are being lazy shits
