### ISSUE TITLE
Chef doesn't have a cow 

### ISSUE THREAD

**Issue by Stealthkibbler** [FTL13/FTL13#392]
need milk, man.

**Comment by Qustinnus** [comment]
>botany :^)

**Comment by Stealthkibbler** [comment]
> No Botanist :^(

**Comment by Qustinnus** [comment]
>wrench the fridge and plant some nutritional plants :^)

**Comment by Altangy** [comment]
Goats can be milked. The real issue would have been no goats but I think all kitchens now have goats.
