### ISSUE TITLE
brig needs a 'garbage cannon' 

### ISSUE THREAD

**Issue by Stealthkibbler** [FTL13/FTL13#394]
"Prisoners who don't co-operate go out the airlock with the rest of the trash"

**Comment by Qustinnus** [comment]
MAC cannon

**Comment by Stealthkibbler** [comment]
>actuator gets jammed after firing the clown out

**Comment by Qustinnus** [comment]
worth

**Comment by Vivalas** [comment]
This needs to be specific to a map since Aerwhisp has this already.
