### ISSUE TITLE
Some of the wiring on NSV Astaeus should be redone

### ISSUE THREAD

**Issue by Stealthkibbler** [FTL13/FTL13#396]
In some areas the wiring is poorly placed under R-walls making it a pain for engineering to locate a missing or damaged wire if power is out.

http://puu.sh/tpKaE/7e22eb4029.png
shield gen could probably be bumped up, the lighting and camera moved to the bottom so the wiring and piping doesnt end up under the R-walls.

http://puu.sh/tpKdy/f52486c045.png
Detectives office really doesnt need the wiring running through the r-walls like that, the wiring for the windows could just fork from within the room.

http://puu.sh/tpKc6/cff01b6e30.png
Just make the corners plating and have the wires run all the way around, also those grilles are going to be the source of many accidents once cables get power again so honestly the vault should be moved or the grilles should be removed.

**Comment by M11gamer** [comment]
From what I saw on the map this is already resolved. : )

**Comment by Vivalas** [comment]
@Stealthkibbler Reopen if you still have issues / complaints about this.
