### ISSUE TITLE
Orbital Platform conveyors dissapearing

### ISSUE THREAD

**Issue by Stealthkibbler** [FTL13/FTL13#406]
The conveyors that connect the ship with the platform sometimes dont spawn in, causing the crates to get stuck or have to be dragged in manually.

**Comment by Stealthkibbler** [comment]
Still happens http://puu.sh/tN2Iz/2f45c6754e.jpg

**Comment by Altangy** [comment]
Stations and docking have been changed. This should no longer be an issue
