### ISSUE TITLE
SOLAR PANELS

### ISSUE THREAD

**Issue by Cw3040** [FTL13/FTL13#417]
So basically, I'm mainly whining about the lack of solar panels in the ship. Not set up, but just there as an auxillary power source in case of ejecting the SM or some shit.

Since I suck at everything regarding BYOND, including the SM, I am posting here so that someone would add a solars crate in the engine room/CE's office/Engineering Prep Room with X solar panels and X/25 (round up) tracker boards in it.

Pls mappers pls.

**Comment by tylerh95** [comment]
Fixed in #419
