### ISSUE TITLE
Stuff in space doesn't delete when you move the ship / ftl

### ISSUE THREAD

**Issue by tylerh95** [FTL13/FTL13#420]
Just look at the picture. Expected things like blood and any other objects to either be delete, or be left behind

![](https://i.gyazo.com/4ec5667d113038aede77d34bece02f2d.png)

**Comment by monster860** [comment]
Everything in the shield bounds is supposed to come with the ship. It's the little "warp bubble" thing.

**Comment by Qustinnus** [comment]
floating blood is an issue though :^))

**Comment by monster860** [comment]
that's what janitors are for

**Comment by Qustinnus** [comment]
janitors don't get a lot of EVA suits these days. :^))
