### ISSUE TITLE
when opening cargo console but did not dock with station x button for window closing disappearing

### ISSUE THREAD

**Issue by etet2** [FTL13/FTL13#43]
**Problem Description**:
when opening cargo console but did not dock with station x button for window closing disappearing

**What did you expect to happen**: 
i expected to see empty window WITH x button for closing window

**What happened instead**:
empty window WITHOUT x button for closing window

**Why is this bad/What are the consequences:**
Can't close window so i have to walk away without seeing anything for windows to close

**Steps to reproduce the problem**:
make x appear

**Comment by monster860** [comment]
If a window ever does that to you:

Press Alt-Space, and then C.

**Comment by etet2** [comment]
ok

**Comment by CrAzYPiLoT-SS13** [comment]
Explained in #48
