### ISSUE TITLE
Tiles blacked out permaneantly, fixed when in hyperspace

### ISSUE THREAD

**Issue by ItsMyCoolName** [FTL13/FTL13#447]
**Problem Description**:
Some tiles appear to be blacked out, as if obscured by something.

**What did you expect to happen**: 
I expected to see through a tile with no issues
**What happened instead**:
I could not see through an empty space tile.
**Why is this bad/What are the consequences:**
I could not see any objects in certain area of space.

**Steps to reproduce the problem**:
Was inside, went outside. Space tiles black as if obscured by walls.
![dreamseeker_2017-01-28_13-19-15](https://cloud.githubusercontent.com/assets/8962643/22399163/dfa15b62-e55c-11e6-9b09-fcda4b78fac9.png)
![dreamseeker_2017-01-28_13-19-18](https://cloud.githubusercontent.com/assets/8962643/22399164/dfa34f44-e55c-11e6-85d1-22835dff72d1.png)

EDIT: upon leaving FTL, it appears to have gotten worse. Trying to clear cache again.

![dreamseeker_2017-01-28_13-25-06](https://cloud.githubusercontent.com/assets/8962643/22399198/6071e842-e55d-11e6-89d3-a3bd8dd37c36.png)
![dreamseeker_2017-01-28_13-25-10](https://cloud.githubusercontent.com/assets/8962643/22399197/6070a14e-e55d-11e6-8f02-2312345a2b73.png)

Problem seems to be resolved while clearing cache, but it pops up again every jump or two.

**Comment by tylerh95** [comment]
Can confirm this is an issue, I noticed it yesterday. I was a ghost as well.

**Comment by Vivalas** [comment]
Believe this was fixed by Monster.
