### ISSUE TITLE
yellow pipes in atmos

### ISSUE THREAD

**Issue by etet2** [FTL13/FTL13#45]
**Problem Description**:
they are useless only thing they do is send gases into scrubbers pipe and gases will be filtered again so gases won't go anywhere and stay in chambers

**What did you expect to happen**: 
there should be mixing chamber and pumps leading to air supply pipes

**What happened instead**:
yellow pipes are useless

**Why is this bad/What are the consequences:**
traitors can't fuck up ship

**Comment by CrAzYPiLoT-SS13** [comment]
This isn't a station. We are already running out of space, and we can't put the mixing chamber anywhere. Also, traitors should not be able to incapacitate the ship, I'm pretty sure.

**Comment by monster860** [comment]
The yellow loop exists for the sole purpose of feeding gases into canisters.

**Comment by CrAzYPiLoT-SS13** [comment]
Not gonna happen.
