### ISSUE TITLE
FTL Arrival timer keeps resetting

### ISSUE THREAD

**Issue by PotatoOS** [FTL13/FTL13#450]
When the FTL ETA Timer hits 0 the ship should arrive at its location, but sometimes the timer resets and it gets stuck on a loop.

**Comment by Nickvr628** [comment]
It occurs because the z-level that is supposed to be loaded for the new location, has not yet loaded.

It is a known issue, but thanks for the report anyway! 😃

**Comment by PotatoOS** [comment]
oh okay
