### ISSUE TITLE
Deck of cards in a big disappearing from inventory when merged with a card from outside a bag.

### ISSUE THREAD

**Issue by Tombomcbombo** [FTL13/FTL13#453]
**Description of bug:**
Deck of cards in a big disappearing from inventory when merged with a card from outside a bag.

**What did you expect to happen**: 
I expected the deck to merge as per usual.

**What happened instead**:
The deck of cards disappeared, just leaving the single card I was trying to merge it with.

**Why is this bad/What are the consequences:**
While not the biggest issue, due to the limited decks of cards available on the map (I've only located one so far: the bar) it can get in the way of bar RP or simple card games. 

**Steps to reproduce the problem**:
1. Draw a card from a deck, keep it in one of your hands.
2. Put deck of cards into a bag (I was wearing a grey duffle bag on my back at the time)
3. Ensure the card is in your active hand
4. Drag the deck of cards into the card in your hand
5. **Poof!**

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?):** To my knowledge nothing was different about this specific round that would effect the bug, and I do not know what the gamemode was.

**Comment by Vivalas** [comment]
Probably should report on TG as well, unless they already fixed this.

**Comment by Tombomcbombo** [comment]
Honestly don't like most of the TG admins/staff anyway. So I can't be bothered to make another post on their forums.

**Comment by Vivalas** [comment]
You probably would have better luck posting about this on their Github anyways. I'll check to see if they already have a fix for this.
