### ISSUE TITLE
Lawyers spawns at brig they can't exit

### ISSUE THREAD

**Issue by ghost** [FTL13/FTL13#456]
**Problem Description**:
Lawyers spawnpoint was set to Brig, where they got no access.

**What did you expect to happen**: 
Lawyer makes his way out of the brig.

**What happened instead**:
Lawyer trapped at brig FOREVER.
![image](https://cloud.githubusercontent.com/assets/21173332/22441873/f845e822-e75a-11e6-8dc9-7b294d1ad5e6.png)

**Why is this bad/What are the consequences:**
You can defend crew rights only through comms.

**Steps to reproduce the problem**:
1.Be lawyer at roundstart

**Comment by ToGWtF** [comment]
#431

**Comment by ToGWtF** [comment]
Also theres no god damned camera on the map for the lawyer (spawn one in briefcase plis)

**Comment by Vivalas** [comment]
Might be outdated, please re-open if it is still an issue,
