### ISSUE TITLE
No library [TUNING FORK / TRAILBLAZER]

### ISSUE THREAD

**Issue by Ecbrd** [FTL13/FTL13#457]
**Problem Description**:
The NSS Astraeus still does not contain a library.

**What did you expect to happen**: 
I expected there to be a library aboard the NSS Astraeus

**What happened instead**:
There is still no library aboard the NSS Astraeus

**Why is this bad/What are the consequences:**
The ship needs books and a place to store them. Dorms, the hallway and that one room with the lockers in it are not very good places for books as they provide neither the resources, the tools or the space for book writing and reading.

**Steps to reproduce the problem**:
Oh, it was horrifying, officer. I logged on and, of course, selected my main during character setup, the one and only librarian, master of pen and paper, the watcher of the sacred ground that is the library- only, something was missing here. I entered the game, beginning to search for the library, later to realise that there was no library to be found. I searched high and low and after the HoP broke the news, I was positively **_mortified_**. I came running to the suggestions page, knowing that the cool and benevolent space gods could help me with this crippling issue as a librarian.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 
I needed to check the wiki for over five minutes to find the name of the god damn ship.

### And yes I am one hundred percent serious about this

**Comment by Qustinnus** [comment]
no

**Comment by M11gamer** [comment]
It's a warship, not a station, the most you can get is a few books in the bar, and that's it. : )

**Comment by Ecbrd** [comment]
It isn't necessarily a warship, it has a bar, and that isn't something you'd need on a "warship"

**Comment by GriffinMan4455** [comment]
A bar is for the recreation of the crew, and to keep morale high.
A library would be there literally only for people to read spaceship erotica

**Comment by Ecbrd** [comment]
And spaceship erotica doesn't boost morale? ( ͡° ͜ʖ ͡°)

**Comment by Greenpoison** [comment]
Have to admit, we do need dedicated storage for The Lusty Xenomorph maid.

**Comment by ninjanomnom** [comment]
#notabug
