### ISSUE TITLE
When the ship enters orbit a vast quantity of the captains plasma fueled ego spills fourth onto the landing site.

### ISSUE THREAD

**Issue by Stealthkibbler** [FTL13/FTL13#464]
http://puu.sh/tMZvx/f8da7640e9.jpg

**Comment by Qustinnus** [comment]
@monster860 this has happend for ages.

**Comment by Psyentific** [comment]
looks like there's some N2O in the middle of that cloud? might be related to the engine or the atmos tanks, both have N2O and plasma in proximity.

**Comment by ninjanomnom** [comment]
probably fixed, new shuttle code new bugs
