### ISSUE TITLE
Stuttering Issue

### ISSUE THREAD

**Issue by Stormc12** [FTL13/FTL13#467]
**Problem Description**:
The game freezes for a few seconds, including sound, preventing you from doing anything (you can still use commands like "say," but they don't go into effect until the game resumes.) Once it resumes, all sounds played during the freeze will play at once, and if you decided to mash the move buttons on the keyboard, you'll be in a random spot.

**What did you expect to happen**: 
It happens only on this server and not any other.

**What happened instead**:
It lagged and stuttered, that's what.

**Why is this bad/What are the consequences:**
Others who don't have this issue can go after those who do indeed have this issue, as they are helpless to do anything but wait.

**Steps to reproduce the problem**:
Issue seems to occur a lot during FTL travel, having the ship be in space, having the ship be on a lava planet, and spooling up.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Not really. Just working as a janitor.

**Comment by monster860** [comment]
It looks like you might be experiencing this thing called "lag"
