### ISSUE TITLE
Ship is unable to be jumpped by crew from nav console but Staff can.

### ISSUE THREAD

**Issue by Altangy** [FTL13/FTL13#472]
**Problem Description**:
The ship nav console stated that the ship was docked but it wasn't players reported that they couldn't jump but the administration team was able to through Admin A.I. interaction

**What did you expect to happen**:
It was expected that the ship would jump when the players attempted to plot a course.

**What happened instead**:
The players were unable to jump the ship while admins were able to.

**Why is this bad/What are the consequences:**
If the player's can't jump the ship, they are stuck in system.

**Steps to reproduce the problem**:
The crew have two of theories behind it:
Landing on a planet and then quickly taking off.
The abandoned teleporter was on the same Z-level.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
It appears the glitch persisted after we jumped it. After a few people have died it looks like the ship z-level thinks it's in lava-land.

**Comment by Altangy** [comment]
I'd like to add that the escape shuttle broke.
![image](https://cloud.githubusercontent.com/assets/25562238/22624987/546b1068-eb58-11e6-8f36-f90d495db0e1.png)

**Comment by Vivalas** [comment]
Haven't seen this in a while, closing for posterity.
