### ISSUE TITLE
Add mime job.

### ISSUE THREAD

**Issue by Bekons** [FTL13/FTL13#474]
**Problem Description**:There is no Mime Slot.

**What did you expect to happen**: With a clown and no mime? It must be a bug.

**What happened instead**:I joined and there was no mime slot.

**Why is this bad/What are the consequences:**There is one less fun job on the ship that is there for pure enjoyment and misery of lesser beings.

**Steps to reproduce the problem**:Add a mime job. And a theathre.

**Comment by Stealthkibbler** [comment]
Map even has a mime spawner, but no mime job slot. 👎

**Comment by Greenpoison** [comment]
I don't personally see the purpose of adding a mime, as amusing as it is I don't believe it would aid roleplay particularly.

**Comment by yobob591** [comment]
I mean what does the clown do anyways, might as well have a mime too

**Comment by ike709** [comment]
Mime job is commented out in the code. @Vivalas

**Comment by Vivalas** [comment]
@Ecolli Is the mime nazi.
