### ISSUE TITLE
Roboticists have full science access, but not the entrance.

### ISSUE THREAD

**Issue by GriffinMan4455** [FTL13/FTL13#477]
**Problem Description**:
Roboticists have access to all of the science division except the main entrance.
**What did you expect to happen**: 
Why do you think this is a bug?
Why would they not have access there?

Why is this bad/What are the consequences:
 Robo has to make a longer trip for no reason

**Steps to reproduce the problem**: Try to use the main entrance and you can't
The most important section. Review everything you did leading up to causing the issue.

**Comment by checkraisefold** [comment]
@monster860 issue resolved, tested on git copy of FTL13 and no signs of the error as roboticist. able to go through main sci doors.
