### ISSUE TITLE
Teleprods wont work

### ISSUE THREAD

**Issue by Stealthkibbler** [FTL13/FTL13#489]
Batteries dont have enough power to charge the prod, even hyper capacity.

**Comment by Qustinnus** [comment]
yeah it's been a problem for a bit now but im too lazy to patch it.

**Comment by Funce** [comment]
@Vivalas This is 100% Fixed. I should've linked this in my PR, but I had no idea it also affected this.

**Comment by Funce** [comment]
@ninjanomnom Wee Vivalas may have missed this one.
