### ISSUE TITLE
A very wishful wish

### ISSUE THREAD

**Issue by Idontcareacount** [FTL13/FTL13#499]
I don't know if this has been suggested before, or is just a really unpopular opinion, but i think ship building should be added to the game. This could be a very versatile way to do combat, with a fleet of ships, instead of one ship. It could also serve as a way to get people back and forth from bases, without having to land at every one of them when the miners eventually kill themselves or get bored, and, is a great alternative to the mildly overpowered quantumpads and teleporter station. Now, even if we don't want to remove quantumpads and telle-stations from the game, it is still a great combat mechanic and a great reason to actually go into a salvage map, beside "get syndicate documents."

**Comment by Nickvr628** [comment]
Factions "build" additional ships in the background, also there is currently a rudimentary"wingman" system, is that what you mean?

Or are you referring to having multiple player ships?

**Comment by Idontcareacount** [comment]
yes that is what i was thinking, for their to be multiple player ships, mostly to see how hilarious it will be as the captain tries to command a fleet of idiots. bust actually because it seems like a cool mechanic.

**Comment by monster860** [comment]
I feel like it would make more sense for NT ships to just be able to ship crew members to places. I actually already have plans for a system for ships to pick up crew members that are left behind.

**Comment by Stealthkibbler** [comment]
It would be very taxing on the server to have multiple z-levels being loaded at once would it not? It already delays when generating and wiping a single pair.

**Comment by yobob591** [comment]
I mean you could have the NT ship pick them up immediately after they are left behind in order to stop many z levels from loading

if you really wanted to abuse it you could drop one person every time you jump but that would be quickly shot down by admins
