### ISSUE TITLE
Cloning Pod Print Bug

### ISSUE THREAD

**Issue by LordWalnut** [FTL13/FTL13#503]
**Problem Description**: When you click on the cloning pod as a ghost, it decides to print out the 'Examine' Text twice.
What is the problem?

**What did you expect to happen**: For it to print once.
Why do you think this is a bug?

**What happened instead**: It printed it twice.
How is what happened different from what you expected?

**Why is this bad/What are the consequences:** It's not too bad, but it's a bug, bugs should be fixed.
Why do you think this is an important issue?

**Steps to reproduce the problem**: Click on the cloning pod as a ghost
The most important section. Review everything you did leading up to causing the issue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us. Nothing interesting was going on, I was not doing anything at the time, apart from checking the status of a clone. And I can't tell you anything else.

**Comment by Spacemanspark** [comment]
Technically not a bug; an ordinary crewmember can click directly on the cloning pod to find out how far the process has come without the need to examine it. I'm presuming that this feature also goes to ghosts.

**Comment by LordWalnut** [comment]
That's not what I said.

**Comment by LordWalnut** [comment]
If you click it as a ghost, it prints it twice. It should only do it once.
