### ISSUE TITLE
Library equipment cannot be constructed

### ISSUE THREAD

**Issue by Ecbrd** [FTL13/FTL13#508]
**Problem Description**:
There are no circuit boards for my **precious library equipment**

**What did you expect to happen**: 
I had expected someone to be arsed making circuit boards for like the most important things in the game

**What happened instead**:
there are no library equipment circuit boards

**Why is this bad/What are the consequences:**
If you fucks aren't just going to give me library equipment at least let me build it myself

**Steps to reproduce the problem**:
Everyone type in the discord chat @Ecbrd is a stupid librarian

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: The Ship's name is still nowhere to be found on the wiki

**Comment by Funce** [comment]
Fixed in #526 
@monster860 Closable.
