### ISSUE TITLE
RCDs can build only two walls before requiring a refill

### ISSUE THREAD

**Issue by GriffinMan4455** [FTL13/FTL13#510]
RCDs are useless right now. You can build two walls before it needs to be refilled. It literally makes them useless
Gaben please fix

**Comment by GriffinMan4455** [comment]
*Addition* I forgot to mention, the RCD was Autolathe-built, if that has any effect

**Comment by Funce** [comment]
@GriffinMan4455
Have you tested this more recently?
Is it still the same?

**Comment by GriffinMan4455** [comment]
I have not tried it since I posted the issue, no. I'll get on in a while to try it out.

**Comment by Psyentific** [comment]
RCDs can do a lot more than two walls, but you still run out of juice pretty fast if it's all you use. It's great for quickly patching a breach, and that's what it's designed to do.

Notably, Engineering's tool vendor has about 3 RCDs, but does not stock Compressed Matter Cartridges (RCD refills).

**Comment by ninjanomnom** [comment]
This was never a bug even from the beginning. Autolathe created RCDs just start with less matter.
