### ISSUE TITLE
People can use issues and PRs to IC in OOC as well as other things

### ISSUE THREAD

**Issue by yobob591** [FTL13/FTL13#516]
**Problem Description**:
Title

**What did you expect to happen**: 
It to not happen

**What happened instead**:
It happened

**Why is this bad/What are the consequences:**
People can spam, IC in OOC stealthily, etc

**Steps to reproduce the problem**:
Open a thing

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Personally I'd remove the feature cause its hard to track whos doing it, but eh

we had the exact same issue after hippie rebase and we just removed it, it wasnt really missed

**Comment by monster860** [comment]
There fixed
