### ISSUE TITLE
Add a preference for xeno ghost roles because if I wanted to be spammed with lusty xeno maids I would have browsed danbooru

### ISSUE THREAD

**Issue by Stealthkibbler** [FTL13/FTL13#521]
it's actually cancer, it cancels typing during a ticket and pushes itself above admin panels.

**Comment by Funce** [comment]
![image](https://cloud.githubusercontent.com/assets/14105827/24779249/470b0bca-1b83-11e7-8da4-2dc77607a78f.png)
Strangely enough this preference includes 70% of the ghost roles, including sentient animals, slaughter demons and of course Lusty Xeno Maids.
