### ISSUE TITLE
Spawned spacepod keys dont lock or unlock the spess pod

### ISSUE THREAD

**Issue by Stealthkibbler** [FTL13/FTL13#522]
rare scenario that a miner gets marooned during ftl warp but its annoying to say the least

**Comment by monster860** [comment]
You're not spawning them correctly, you need to set the id of the key to 5318008

**Comment by Stealthkibbler** [comment]
Shouldnt it automatically set the id to 5318008 since at any and all times there's only ever one spacepod?

**Comment by monster860** [comment]
No the mapped in locks and keys have ids of 5318008

**Comment by monster860** [comment]
It does round to 5.31801e+006

**Comment by Stealthkibbler** [comment]
Couldnt you just set the default id for the keys in their respective directory
