### ISSUE TITLE
Industry Idea for Ice Planets

### ISSUE THREAD

**Issue by Stealthkibbler** [FTL13/FTL13#527]
At the moment the only lucrative trade source is minerals, meaning lava planets are just about mandatory for every round if the crew ever want to do long term trading, even then mining isn't exactly a very engaging or fun experience as it's been around for a long time. 

**Ice Planet Industry**
Ice Planets are well, Ice, Cold and while they are just a flat ice sheet they have a pretty decent atmosphere for what they are. A fun an intuitive Industry for crew to engage in would be **Ice Fishing**.

Simply put the crew construct a small structure above the Ice by smashing the ice sheets open using a pickaxe or shovel, they are then able to place tiles over the now shattered ice sheets, once they are done setting up a space heater, getting some nice warm dutch coco and robusto coffee they can begin fishing over one of the broken ice sheets. To do so they would need to construct a sonic pulser, in simple terms a 1x1 Metal machine that rolls the dice to spawn carp.

**Sonic Pulser**
The Pulser would send out sonic pulses when turned on, triggering the carp below and forcing them into a frenzy as they spawn at the pulser. The Pulser would have two functions, **Depth** and **Intensity**. **Depth** would affect what types of carp on an integer based scale are caught in the dice roll, while **Intensity** affects how many of them are spawned at a time.

**_Possible Carp Variations**

- Common Ice Carp, found at any shallow depth.

- Ice Megacarp, Ice variant of the Megacarp, found at shallow depth but more rare than common carp.

- Angler Carp, Found at Deep Depths, very dangerous.

- Coral Carp, Found at Sea Bed Depth, Extremely Poisonous.

- Crystalline Carp, Found at Sea Bed Depth, Rare and always drops rich minerals and treasures.

**Benefits and Cons**

**Benefits**

- A Streamlined supply of fillet for the chef

- The Mystery and desire to see what horrors can be pulled from the depths of the sea.

- Possibility to start up a fish gladiatorial arena for bored crew

- Carp would have a chance to drop rare treasures, gems, gold, minerals and maybe artifacts when butchered that would fetch a hefty price at trade stations.

- Possibility for xenobio to sentience one of the unique carp so the crew can have their own pet scurvy sea fish.

- Actual Carp Crafting Mats in the form of special scales so crew could craft unique and custom carp clothing so that they can survive the freezing temperatures in style and glamour and impress all their jealous spess mates while doing so.

**Cons**

- Extremely cold temperature, winter wear and hardsuits are mandatory to operate in such harsh conditions.

- Carp are always hostile, leading to much fish wrassling.

- Some Carp carry deadly toxins that could range from the common toxin to deadly hemotoxin or even a special type of Teslium.

- Much harder to setup a working power net and atmos filter system compared to lava planets.

- Space Heaters mandatory if long term living is to ever be a thing

**Comment by Qustinnus** [comment]
seems overscoped and gimmicky. if you code it id be fine with it being merged.

**Comment by Stealthkibbler** [comment]
Honestly the hardest part would be the pulser and different carp types, other than that it'd be just like setting up a colony on any other planet

**Comment by Qustinnus** [comment]
But there's not much purpose for it, mining isn't done yet so it's boring atm.

**Comment by Stealthkibbler** [comment]
Yeah but fish gladiatorial arenas and carp wrassling

10x better than smashing rocks all day

**Comment by Qustinnus** [comment]
but it is not a priority so you'd have to code it yourself.

**Comment by Stealthkibbler** [comment]
Ill code ur face
