### ISSUE TITLE
Industry Idea for Gas Giants

### ISSUE THREAD

**Issue by Stealthkibbler** [FTL13/FTL13#528]
This is a continuation of #527 

**Gas Giant Industry**
Gas Giants at the moment serve no purpose other than to be a placeholder, however I see a huge potential for them to act as a major facilitator in the current player driven economy.

For a first the ship would be able to 'land' on the gas giant, technically speaking the 'land' of the giant would just be an empty re-textured space tile with a purple palette to it as Gas Giants are just giant planets of pressured gas with no hard surface.

**Irregular Gas Giants**
Realistically Gas Giants are made up of Hydrogen and Helium, but for the sake of 2D spessmens we'll go with the assumption that all Gas Giants are PLASMA GIANTS! Now while I would love the idea of different types of gas giants, I feel like keeping it simple and easy is the best way of going about this. Simply put, Plasma is the most valuable gas, having the other gases would be obsolete since plasma exists.

**Gas Extraction**
This is probably an extremely simple, yet very dangerous and volatile method of making monies, after building a functioning Rig; simply one or two rooms the crew would deploy a gas drill, this drill would need to be connected into a pipeline that could branch into connectors or even separately built chambers depending on how much bang for their buck the crew want to do. Then from the activation of the drill it would begin pumping and filtering pure plasma into the pipeline, which is then pumped into canisters via connector ports and sold at stations or stored for later use.

**Benefits and Cons**
**Benefits**

- The most rewarding and consistent method of turning a profit at trade stations.

- Many of the materials needed to jumpstart a drill operation are available at the start of the round.

- The ability to store the plasma canisters for later use saving you lots of cargo points in the long run.

- A fairly simple and straightforward method of trade.

**Cons**

- The bone crushing pressure and volatile fumes of the Giant make Exosuits/Hardsuits and Internals mandatory.

- Exposing the atmosphere to pure oxygen or an open flame could lead to extremely !FUN! moments.

- Requires basic atmospherics knowledge to setup.

**Comment by Qustinnus** [comment]
how the fuck do you land on a gas giant

**Comment by Stealthkibbler** [comment]
Theoretically it would work the same way with any other planet, except instead of the tiles being normal turf, they would be a foggy purple to resemble them being dense gas and there would be no gravity.

**Comment by Nickvr628** [comment]
Use plasma floor tiles and stupidly high pressure that will slowly break the ship's windows if they stay too long. :)

**Comment by Stealthkibbler** [comment]
Totes make plasma composed dust devils the natural fauna.

**Comment by Ecbrd** [comment]
alternatively you could get some lemons and mutagen to get infinite monies

**Comment by Utmanarn** [comment]
I kinda Like it
