### ISSUE TITLE
Permissions panels admins are not saving

### ISSUE THREAD

**Issue by monster860** [FTL13/FTL13#56]
**Problem Description**:
Permission panel admins are not saving on MySQL

**What did you expect to happen**: 
For permissions panel admins to save on the mysql database

**What happened instead**:
I have to readd the admins every round

**Why is this bad/What are the consequences:**
Because then admins can't do admin things

**Steps to reproduce the problem**:
1. Add admins with perms panel
2. Restart server
3. They're not there next round.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by CrAzYPiLoT-SS13** [comment]
@monster860 Just found out /tg/'s database admin system does not work. We should revert to legacy.
