### ISSUE TITLE
Command Consoles Display "Call" instead of "Arm" escape shuttles.

### ISSUE THREAD

**Issue by Epicworlds** [FTL13/FTL13#572]
**Problem Description**:
The command console displays Call instead of Arm

**What did you expect to happen**: 
I expected it to say Arm shuttles instead of Call shuttles
**What happened instead**:
It says Call shuttle

**Why is this bad/What are the consequences:**
Just confuses me 

**Steps to reproduce the problem**:
Go and click on a communications console

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Vivalas** [comment]
>Autism
