### ISSUE TITLE
Add the ability to cancel the FTL after 30 seconds into launch squence.

### ISSUE THREAD

**Issue by Epicworlds** [FTL13/FTL13#573]
I think you should be able to do a Safety Override on the navigation computer if you have the captain swipe a ID at the same time as a BO that cancels the FTL after safe processing time. The negative effect of this would vary as time progresses. If you cancel it at 20 seconds you might have some pipes burst in the engine room. If you do it at 10, you run the risk of causing some major damage. 5 seconds to launch could result in a explosion.

**Comment by Epicworlds** [comment]
(Feature Request, Not a bug)

**Comment by Vivalas** [comment]
Currently isn't possible without sound fuckery and honestly I don't like this idea at all. You have 30 seconds to cancel and after that bon voyage.

To clarify on sound fuckery all the wierd sounds and shaking and shit start happening after 30 seconds.
