### ISSUE TITLE
Gibber in chef's kitchen produces an extremely large amount of gibs and meat

### ISSUE THREAD

**Issue by nervere** [FTL13/FTL13#575]
![monkey gibs](https://cloud.githubusercontent.com/assets/26285377/23720719/7309460c-040d-11e7-99f0-3f189015f4d8.png)

**Problem Description**:
What is the problem?

When gibbing something like a monkey in the gibber in the kitchen, a lot goes wrong. (I have not tested this for human corpses.) First off, there is about 40 pieces of meat produced. Secondly, there is an equal amount of gibs to go with the meat. There is, as you can see in the screenshot, a full list of gibs in a single tile. There is even more in places where you can't see it and can't clean it, such as under the steel tables where the chef puts food and supplies on. It's extremely laggy and seems to lag the server a lot until all of the gibs finish processing. With multiple corpses, the server could potentially crash the people playing, or maybe even the server.

**What did you expect to happen**: 
Why do you think this is a bug?

I expected to get a normal amount of meat from the monkey corpse that I gibbed. Note that the meat is labelled "Monkey II meat" only because the monkey was labelled "monkey II meat." It's the same as gibbing someone called "John Smith" and getting "John Smith meat."

**What happened instead**:
How is what happened different from what you expected?

I got about 40 pieces of meat and hundreds of gibs all over the place.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?

Potential client/server crashes.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

Kill a monkey (make sure he is dead. I did this multiple times to test it out to make sure it wasn't just a one time thing, and they were death both times. I don't know if there is a different result if the monkey is alive.) and then insert him in the gibber. Click the gibber only one time to chop the monkey up.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

I tested this over three rounds, I don't think it matters based on what round it was. Nothing else out of the ordinary was happening. We were not in FTL travel nor were we preparing for it.

**Comment by DerekPlays** [comment]
I can't reproduce it, have you tried hard restarting your server?
