### ISSUE TITLE
Slime Management Console issue

### ISSUE THREAD

**Issue by Xxxretroxgears3** [FTL13/FTL13#59]
**Problem Description**:
Stuck on Slime Magnent Computer
**What did you expect to happen**: 
It will not let me exit it
**What happened instead**:
I thought it would work but did not
**Why is this bad/What are the consequences:**
It's game breaking

**Steps to reproduce the problem**:
The most important section. Use the consule

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by CrAzYPiLoT-SS13** [comment]
It works well. You just need to use the 'End Camera View' action button in the top left.
