### ISSUE TITLE
Supply request console in Cargo fails to load.

### ISSUE THREAD

**Issue by hecksadecimal** [FTL13/FTL13#6]
The supply request console opens a window that says 'Loading...', and never completes.
Furthermore, no window elements exist to close the window during this moment.

The window can be resized, but not moved or closed. 

![example_problem](https://cloud.githubusercontent.com/assets/20251491/16947082/f3ca6eb4-4d7a-11e6-8a65-4b74ca5d7552.PNG)

Supply console further up displays the exact same behavior.

**Comment by CrAzYPiLoT-SS13** [comment]
I'm sure it's just because this is a work in progress. Still, thanks for
documenting this issue.

**Comment by hecksadecimal** [comment]
That's all this was for. Documentation.

**Comment by monster860** [comment]
Probably because the map doesn't have a supply shuttle docking port. The supply system is going to have to be rewritten.

**Comment by monster860** [comment]
Well, shit's fixed with the new trading. Sort of.
