### ISSUE TITLE
Engineering Vendor won't vend for engineering

### ISSUE THREAD

**Issue by Chickenmonster1** [FTL13/FTL13#60]
**Problem Description**:
What is the problem?
Engineering Engivendor does not allow engineers access to it by default
**What did you expect to happen**: 
Why do you think this is a bug?
The engineering vendor should work for engineers
**What happened instead**:
How is what happened different from what you expected?
^
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
It makes us have to hack it and make it work for everyone
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by monster860** [comment]
@CrAzYPiLoT-SS13 god damn it

**Comment by CrAzYPiLoT-SS13** [comment]
Why am I so fucking stupid
