### ISSUE TITLE
Minimap is cutoff

### ISSUE THREAD

**Issue by ike709** [FTL13/FTL13#604]
![image](https://cloud.githubusercontent.com/assets/5714543/24583679/d9fdbae2-1717-11e7-86c7-975837f25336.png)

@Shadowlight213 The bottom and right sides of Aetherwhisp minimap are cutoff. Dunno if this happens on other maps.

https://github.com/FTL13/FTL13/pull/590

**Comment by Shadowlight213** [comment]
Damnit I thought I fixed that on my last test before commit.
I'll try and find time to fix this tonight.

**Comment by ninjanomnom** [comment]
This is fixed last I checked
