### ISSUE TITLE
Engineering needs a few more air control monitors

### ISSUE THREAD

**Issue by Chickenmonster1** [FTL13/FTL13#61]
**Problem Description**:
What is the problem?
There is only one air control monitor in engineering
**What did you expect to happen**: 
Why do you think this is a bug?
it's not a bug
**What happened instead**:
How is what happened different from what you expected?
N/A
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Slightly, but it would be nice to have at least one in the SM room to toggle depending on the situation.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by CrAzYPiLoT-SS13** [comment]
What do you mean by air control monitor? The atmospheric alert console?
