### ISSUE TITLE
FTL and Shield Systems refuse to charge plasma

### ISSUE THREAD

**Issue by Altangy** [FTL13/FTL13#612]
**Problem Description**:
What is the problem?
FTL and Shield Systems refuse to charge plasma thus not allowing them to function. Sometimes they will "eat" the plasma, destroying it but not using it
**What did you expect to happen**: 
Why do you think this is a bug?
I don't think we want faulty systems. At least with no way to repair it.
**What happened instead**:
How is what happened different from what you expected?
I expect the plasma to be used by the systems so they can function. To fix this I or another admin need to set the plasma_charge_max to 0 so the systems can function without plasma, but that's only a hotfix that goes around the issue.
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Considering the FTL and Shield Systems use plasma at round start and need an admin to get around the issue and both systems are integral to play, I'd say that it's a really big issue.
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
It sometimes happens at round start and sometimes at random intervals within the round. When it starts, the issue persists till server restart which then RNG determines when the systems stop accepting plasma again. This is not the run of the mill "It's the pipes being bitchy and need to be configured a certain way" as even unaltered, round start, pipe setups become glitched.
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
The issue has occurred for multiple rounds and I personally noticed it during the week of March 31 to April 2

**Comment by ninjanomnom** [comment]
It's important to note that this only sometimes happens. From testing it looks like the terminal_process_atmos proc isn't being called at all but I'm still unsure.

**Comment by Psyentific** [comment]
seems to happen with recycled canisters or dirty pipes (ie stray mole of non-plasma gas). a pr about that got merged the other day, not sure if that fixed it.

also happened earlier tonight. we'd hooked the scrubbers loop up to the ftl/shields and used a gas filter to route only plasma into the ftl/shield intakes, but we ran into issues when the loop was superpressurized (ex >9000kpa) which were resolved once we brought the pressure down to reasonable (~1000kpa?) levels.

**Comment by Psyentific** [comment]
doesn't seem to be happening anymore. at least, no issues on the easter weekend, so thanks codebros

**Comment by ike709** [comment]
@Vivalas This was fixed

**Comment by ninjanomnom** [comment]
@monster860 @Vivalas DELET THIS
