### ISSUE TITLE
ships.dm runtimes like cray cray

### ISSUE THREAD

**Issue by ike709** [FTL13/FTL13#623]
![image](https://cloud.githubusercontent.com/assets/5714543/24824411/1d7e24b6-1bd0-11e7-8a78-c10e9fafdf3c.png)

I was fucking around with the MAC on my local server, and after a few minutes in I got spammed with that runtime A LOT. I never left dock or anything, just sat around in Munitions for a bit.

**Comment by Vivalas** [comment]
Wow this one is pretty weird actually.

**Comment by ike709** [comment]
@Vivalas Possibly happens when ships are jumping between planets in a system? I know FTL makes a bunch of other shit null during FTL.

**Comment by Vivalas** [comment]
No the issue is the spool_ftl() proc being fed a bad target system.

**Comment by ike709** [comment]
![Alt Text](https://t.gyazo.com/teams/nomemeshere/9c774d1035d123c64231b6548cddc2fb.gif)

@Vivalas AHHHHHHHHHHHHHHH

**Comment by ike709** [comment]
https://github.com/FTL13/FTL13/issues/705 is a dupe of this with more details
