### ISSUE TITLE
SuperMatter Bug

### ISSUE THREAD

**Issue by HuskyDog** [FTL13/FTL13#63]
**Problem Description**:
The Emitter does not shoot when the shutters are closed, we are forced to leave them open.

**What did you expect to happen**: 
It ruins the game. Everybody starts to hallucinate

**What happened instead**:
I expected the emitter to have a spot to shot through.

**Why is this bad/What are the consequences:**
It semi-ruins the game.

**Steps to reproduce the problem**:
Setup the supermatter. Turn shields on.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: No

**Comment by monster860** [comment]
Solution is simple: Just don't walk into the engine room without mesons.

**Comment by julian94** [comment]
I'm pretty sure that this is working as intended.

**Comment by HuskyDog** [comment]
Then what are the purpose of the shutters?

**Comment by julian94** [comment]
Because you should probably not have the emitter on constantly, but I might be wrong on this codebase.

**Comment by Vivalas** [comment]
Most codebases with SM have two buttons, one for the main shutters, and one for the "ignition port" or the shutter that blocks the emitters.
