### ISSUE TITLE
Ship is able to "double jump," and deletes itself upon doing so.

### ISSUE THREAD

**Issue by nervere** [FTL13/FTL13#636]
**Note: this happened from 10:45 EST to 11:10 EST on April 9th, 2017, in case server logs are important to this issue.**

**Problem Description**:
What is the problem?

The ship is able to do a double FTL jump. Once it does this, everyone dies to a "hyperspace ripple," the ship is deleted, and any items that were on the ship just stay where they were. Upon this happening it appears the shuttle was automatically called. It could have been a staff member who called it, however, because there was one online when this happened.

**What did you expect to happen**: 

The ship only would jump once.

Why do you think this is a bug?

I doubt that everyone aboard the ship dying and the ship either a.) teleporting to another system with no one on it or b.) the ship getting deleted (there's no way to tell if it was deleted or just teleported away) is an intended feature.

**What happened instead**:

Instead of a single jump, everyone died, and the ship was gone.

How is what happened different from what you expected?

It probably shouldn't have killed everyone and deleted the ship.

**Why is this bad/What are the consequences:**

Everyone dies. Ship is deleted. Without an admin, you have to wait for the shuttle to arrive (usually 25 minutes with the ship on alert level green). This is assuming the shuttle is automatically called, though, because we did have a staff member online when this happened.

Why do you think this is an important issue?

It kills the server population, it kills all of the players, and it can instantly ruin everyone's round.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

This is where things get a bit fuzzy, because even the bridge staff are a bit unsure as to how this happened. I'll list the two ways that the crew think it happened. I was the Quartermaster, so I didn't experience these first-hand.

Method A.)
1.) Initiate a FTL jump.
2.) Cancel the jump.
3.) Before it cancels (it takes a few seconds), initiate a new jump.

Method B.)
1.) Initiate a FTL jump.
2.) Immediately have a second person initiate a second one within the same star. (ex. planet-to-planet jump)

(Maybe this is related to this FTL drive draining plasma really quickly, so the ship is able to recharge for a second FTL jump extremely fast?) There methods are a bit weird and probably aren't able to reproduce, but when I asked the bridge crew how it happened, this is the best that they could give me.

**Possibly related stuff (which gamemode was it? What were you doing at the time?**

Gamemode was extended, as usual. I was just using the autolathe. The ship was leaving from one syndicate star to another. We were not docked at a station when this happened.

Was anything else out of the ordinary happening?)**: 

No, nothing else weird was happening when this happened.

Anything else you can tell us.

Below is a chat log, along with two screenshots of what happened and the carnage. Notice that in the chat log, there are two consecutive FTL spool-ups, with the first one not being cancelled.

Chat log: 

https://pastebin.com/8Xk7wxC6

Screenshots:

![hyperspace ripple](https://cloud.githubusercontent.com/assets/26285377/24838470/72b3428a-1d16-11e7-9ec9-8cde79492af7.png)

![hyperspace ripple 2](https://cloud.githubusercontent.com/assets/26285377/24838474/76eb644a-1d16-11e7-8fc3-5611775f4c03.png)

**Comment by Vivalas** [comment]
Yeah I have a slight suspicion that this is due to race conditions because this hasn't happened in a while and if this is indeed due to FTL cancelling not working.

**Comment by Qustinnus** [comment]
race conditions? I call for genocide.

**Comment by ninjanomnom** [comment]
This ancient bug is fixed now with the ship jumping system now using more proper shuttle procedures.
