### ISSUE TITLE
XO's stamp has no icon

### ISSUE THREAD

**Issue by Vivalas** [FTL13/FTL13#639]
The XO stamp has no icon and is invisible.

**Comment by Vivalas** [comment]
@ike709

**Comment by ike709** [comment]
GOD FUCKING DAMN IT I'LL FIX IT TOMORROW I SWEAR I FIXED IT ALREADY I SPECIFICALLY LOOKED FOR THE STAMP WHEN I MADE THE ORIGINAL PR.
