### ISSUE TITLE
Bridge Hit = ggnore

### ISSUE THREAD

**Issue by Psyentific** [FTL13/FTL13#640]
Right now, if the bridge gets hit, it's basically ggnore. If the hit doesn't outright kill the (usually unarmored, unsuited, no internals) bridge crew, it knocks them out and then there's nobody to either jump away or keep shooting.

I like the bit where the bridge gets hit and all the command crew die.
I don't like the bit where it knocks the ship out of the fight and gives the enemy free hits on us. That usually causes a lot of pain and can end the round.

I propose a sort of 'Battle Bridge' or secondary command post. A ship weapons console and a navigation console, placed somewhere other than the bridge. This would be one of the less-useful heads battle station. 

Possibly Engineering (use the engine control room?), possibly in the Brig (convert the HoS' office?), possibly Maint (above the bar hallway?). It wouldn't need to be a big room, or even a nice room. One chair, two consoles, and a box of donuts.

**Comment by yobob591** [comment]
This

Any military ship worth it's salt has one of these. Modern ships have one in the form of an Operations room in which all the high ranks stay (https://en.m.wikipedia.org/wiki/Operations_room). It doesn't have to work exactly like this but having at least a back up nav console somewhere armored so you can run away until the bridge is fixed would be nice

**Comment by ike709** [comment]
I would suggest the XO's office be modified to support this so it serves more of a purpose than just ID changes, plus it'd give the XO more reason to be in there, but the XO's office is fairly close to the bridge on Aetherwhisp.

**Comment by Vivalas** [comment]
Huh I like this but it needs to be aesthetic. Should also be a requirement for all future maps.

**Comment by Kmc2000** [comment]
I like.


Lemme refork and i'll add this in.
