### ISSUE TITLE
Warning during initialization

### ISSUE THREAD

**Issue by ike709** [FTL13/FTL13#644]
![image](https://cloud.githubusercontent.com/assets/5714543/24930672/e4ab2d02-1ecf-11e7-95ae-4d7e2184d5ae.png)

## WARNING: No /obj/docking_port/mobile/supply placed on the map! in code/controllers/subsystem/shuttles.dm at line 47 src: Shuttles usr: .

It's a thing every round, and has been there forever, so it's not my fault. No clue what it means, I don't hate myself enough to look at shuttles.dm

**Comment by Vivalas** [comment]
It means there is no supply shuttle
