### ISSUE TITLE
Brig access buttons do not work for Sec Officers

### ISSUE THREAD

**Issue by Arrow768** [FTL13/FTL13#65]
**Problem Description**:
The brig access buttons do not work for normal sec officers

**What did you expect to happen**: 
Click the button to open the door

**What happened instead**:
Click the button. Get Access Denied message

**Why is this bad/What are the consequences:**
The security font desk is not very useful

**Steps to reproduce the problem**:
Click the brig access buttons as a sec officer

**Comment by CrAzYPiLoT-SS13** [comment]
I seriously want to make a label for my access fuck ups
