### ISSUE TITLE
Job subsystem runtime

### ISSUE THREAD

**Issue by Vivalas** [FTL13/FTL13#666]
![image](https://cloud.githubusercontent.com/assets/6334647/25066819/0eb97714-21f7-11e7-8758-5eb54cb0c4bb.png)

@ike709

**Comment by ike709** [comment]
I mean it works fine so I don't know what the hell is wrong with it.

**Comment by ike709** [comment]
And it still runtimes less than fire alarms...

**Comment by ike709** [comment]
Also #666

**Comment by Vivalas** [comment]
:fire:
