### ISSUE TITLE
The security camera console in the sec office cant be accessed

### ISSUE THREAD

**Issue by Arrow768** [FTL13/FTL13#67]
**Problem Description**:
The security camera console in the sec office cant be accessed

**What did you expect to happen**: 
Click on the console. Cam window appears

**What happened instead**:
Nothing.

**Why is this bad/What are the consequences:**
Sec officers cant access the console

**Steps to reproduce the problem**:
Go into the sec office.
Click on the console

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: 

It cant be accessed because it is in a corner between the disposals bin and the prisoner management console

**Comment by CrAzYPiLoT-SS13** [comment]
This is actually a map issue, and not my fault.
