### ISSUE TITLE
Engine Core Airlock doesn't prevent atmos contamination

### ISSUE THREAD

**Issue by Psyentific** [FTL13/FTL13#672]
The supermatter engine core needs a vent, scrubber and canister set, as well as pressure equalization. Otherwise, no matter what happens, some of the super-pressurized engine core is going to leak into the main room and that is very bad.

**Comment by Vivalas** [comment]
I'm not following you exactly, what leads to it's eventual contamination?

**Comment by Psyentific** [comment]
Sorry, made this issue while the round was still going.

Take a look at Baymap (or any ZAS really) airlocks. In addition to the usual 'seperate room' thing, there's a vent and canister nearby, controlled by the airlock controller button-thingy, which equalize the pressure in the airlock with the internal/external pressure before opening the door. This is so that, when the door opens, the atmospherics are equal and there's no space wind.

Contrast to our airlocks which have the two-doors to minimize air loss, but they don't have a related vent and canister. End result being that, when you open a space airlock, the ship loses some air.

This is more serious with the engine core, which almost always operates above ambient pressure (ie 101.3kpa). This means that, when you open the core-to-airlock doors, some engine gas comes from the core into the airlock, and since there's no way to store or vent the contents of that airlock, it winds up in the main engine room.

![image](https://cloud.githubusercontent.com/assets/6664133/25079037/a94ab3fa-22ed-11e7-9aee-35f00cf2c31d.png)

Assuming we keep the SM (re: ninja's fancy fusion WIP), we'll need a way to equalize the engine core airlock with both the engine room and the engine core, and while we're at it an identical system to equalize external airlocks with ship atmos and space.

**Comment by Psyentific** [comment]
recommended tags: mapping issue and FUCK

**Comment by Vivalas** [comment]
I think I mentioned this to Aerwhisp but more along the lines of making separate shutters for exterior / interior since contaminations really isn't that bad except for moving the shard around. which maybe is bad. I suppose we could rig this up.
