### ISSUE TITLE
Hard to scan people in genetics.

### ISSUE THREAD

**Issue by julian94** [FTL13/FTL13#69]
**Problem Description**: It's rather complicated to get unconscious/dead people into the scanners. As of now you have to walk into the scanner while they are outside it and then grab their neck to get them in.

**What did you expect to happen**: To be able to drag them right in.

**What happened instead**: I was unable to drag them in due to the layout.

**Why is this bad/What are the consequences:** People might not get cloned after dying.

**Steps to reproduce the problem**: Walk into genetics and try to drag someone in.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Here is an image of a solution that would work.
![nsv jormungandr 2016-07-31 212515](https://cloud.githubusercontent.com/assets/4765643/17278805/58a49900-5766-11e6-9a30-83de8d875fea.png)

**Comment by CrAzYPiLoT-SS13** [comment]
Ugh, goddamned TG shitcode
