### ISSUE TITLE
ALT-TITLES don't show proper icons on secHUDs

### ISSUE THREAD

**Issue by Funce** [FTL13/FTL13#699]
**Problem Description**:
SecHUDs don't show the proper icon for alternate titles.
It just shows the grey 'undefined' dot. Speaking of which the Bofficers don't exactly have any either.
@ike709 

Good luck Friendo's

**Comment by ike709** [comment]
I'm pretty sure I just have to replace a single GetRank with GetPlayerAltTitle so _shrugs_

**Comment by ike709** [comment]
I lied, sechud code is fucking shit.

**Comment by Vivalas** [comment]
I think this is where all those runtimes are coming from.

**Comment by ike709** [comment]
I'm pretty sure it isn't the cause of the runtimes because sechud code checks the assignment on a player's ID against a list of all jobs and returns "Unknown" if it's not on the list. And it current displays "Unknown" for alt titles.
