### ISSUE TITLE
Several runtimes in ships.dm

### ISSUE THREAD

**Issue by ike709** [FTL13/FTL13#705]
![image](https://cloud.githubusercontent.com/assets/5714543/25301705/b2fbcaba-26f3-11e7-9f91-372d9481e9af.png)

**Comment by ike709** [comment]
![image](https://cloud.githubusercontent.com/assets/5714543/25301719/1d03f5a4-26f4-11e7-9de6-1c7a93cc8460.png)

**Comment by ike709** [comment]
Lines that this runtime occurs on: 316, 185, 206, 203, and 211

**Comment by ike709** [comment]
![image](https://cloud.githubusercontent.com/assets/5714543/25301735/5a3a3de8-26f4-11e7-8858-c4f0e08c4990.png)

**Comment by ike709** [comment]
![image](https://cloud.githubusercontent.com/assets/5714543/25301741/6f66fcc4-26f4-11e7-9415-e208277223cb.png)

**Comment by ike709** [comment]
https://github.com/FTL13/FTL13/issues/623 was a less detailed dupe of this so I closed it.

**Comment by Cirrial** [comment]
The ship.dm issue seems like it might be best as a different ticket, it's for ship.dm and not ship**s**.dm.
