### ISSUE TITLE
Battle Bridge is left behind in Undocks/FTL

### ISSUE THREAD

**Issue by Psyentific** [FTL13/FTL13#710]
Issue: 
![image](https://cloud.githubusercontent.com/assets/6664133/25301939/6838b9a4-26e7-11e7-89cb-29747ddb2f1e.png)

Immediately after first undock from station.
It apparently took the construction area with it? I don't know.

**Comment by Psyentific** [comment]
_**TEST YOUR CODE REEEEEEEEEEEEEEEEEEEEEEEEEEEE**_

**Comment by ike709** [comment]
@Kmc2000 boi

**Comment by yobob591** [comment]
holy shit

**Comment by Psyentific** [comment]
related PR: https://github.com/FTL13/FTL13/pull/711
