### ISSUE TITLE
Atmos: N2 and O2 Gas Filters switched

### ISSUE THREAD

**Issue by Psyentific** [FTL13/FTL13#718]
**Problem Description**:
NSV Astraeus: In the new Atmos setup (ie just updated to server now), the N2 gas tank filter on the Pure line (ie green) filters O2 by default, and the O2 gas tank filter instead filters N2. Essentially, left alone it'll mean that the gas tanks get cross-contaminated.

**Comment by ninjanomnom** [comment]
Fixed
