### ISSUE TITLE
SM Gas Filters lose power on FTL

### ISSUE THREAD

**Issue by Psyentific** [FTL13/FTL13#719]
**Problem Description**:
The Supermatter gas filters lose power intermittantly (on FTL jumps?), causing the engine core to lose coolant and quickly explode. Fun fact, that's literally how Chernobyl exploded

**What did you expect to happen**: 
The engine room gas filters should not switch off or lose power of their own volition.

**What happened instead**:
Power loss on the gas filters, leading to empty core with firing emitter, leading to explosion.

**Why is this bad/What are the consequences:**
SUPERMATTER EXPLOSIONS ARE BAD OK

**Steps to reproduce the problem**:
Set up the engine as normal. Perform an FTL jump. Check the gas filters.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: There was also an electrical storm before my instance; that could be related, but I believe that only affects lighting. 

**Possible workaround**: Make gas filters and other pipe-related devices automatically switch on after power failure. That is, if the power fails and the pump/filter was on, then turn back on again as soon as power is available again.

![image](https://cloud.githubusercontent.com/assets/6664133/25310756/fa7dfbac-27a1-11e7-8bb3-7e27606664e4.png)
_IT KEEPS HAPPENING REEEEEEEE_

**Comment by ike709** [comment]
@ninjanomnom

**Comment by Vivalas** [comment]
This should have been fixed by now.
