### ISSUE TITLE
Navigation console unusual behavior?

### ISSUE THREAD

**Issue by Hadrin** [FTL13/FTL13#72]
**Problem Description**:
What is the problem?
Not necessarily a problem, but when the navigation console is accessed and then moved away from, the blips representing nearby star systems turn into lowercase 'a's.

**What did you expect to happen**: 
Why do you think this is a bug?
I expected the blips to remain blips.

**What happened instead**:
How is what happened different from what you expected?
The blips became 'a's

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Not really important, just figured you guys would want to know.

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Joined game as HoP during a secret round.
Accessed navigation console and it appeared normal
Move away from navigation console without closing console window
Look at where the blips used to be

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
It was a secret round, pretty sure it was traitor judging by the bridge bombing a few minutes later. Aside from that I can't think of anything.

**Comment by CrAzYPiLoT-SS13** [comment]
@monster860

**Comment by Funce** [comment]
@Vivalas I don't know what happened, but once upon a time this used to happen but now it doesn't. I'd free this up in case anyone else finds it happening again.
