### ISSUE TITLE
Tactical computer showing ships in other systems

### ISSUE THREAD

**Issue by ike709** [FTL13/FTL13#745]
![image](https://cloud.githubusercontent.com/assets/5714543/25553225/785b20a6-2c73-11e7-843d-27e4ebbad921.png)

@Vivalas

**Comment by Vivalas** [comment]
What context is there for this?

**Comment by ike709** [comment]
@Vivalas What do you mean what context? The ship is in the Ersotere system, targeting is showing ships in the Zaat, Raedarle, and Atma systems.

**Comment by Altangy** [comment]
Odly enough a year later you can still see this happen
