### ISSUE TITLE
Security Officers aren't equipped with everything the code says they should be

### ISSUE THREAD

**Issue by ike709** [FTL13/FTL13#747]
![image](https://cloud.githubusercontent.com/assets/5714543/25558072/ef0d40b4-2ce4-11e7-8031-f98f1d0f08a6.png)
![image](https://cloud.githubusercontent.com/assets/5714543/25558077/0277960e-2ce5-11e7-8759-5d7da550523d.png)

See: Lines 223-225. Picture taken on this GitHub, not one of my branches.

@Vivalas You touched this code last.

**Comment by Qustinnus** [comment]
Remove the armor from there, our service unifroms are apparently armored after checking, Also I will PR an update that will allow them to hold their guns in the suit storage slot so if you want move the gun there and I will PR an update before that to allow the gun to actually be there.
