### ISSUE TITLE
Bluespace minimoog playing

### ISSUE THREAD

**Issue by AuroranAI** [FTL13/FTL13#749]
**Problem Description**:
Drones can play minimoogs at any distance with a bit of help.

**What did you expect to happen**: 
Minimoogs should stop playing when a drone

**What happened instead**:
When the drone is picked up, no check is made to see if the drone is moved, so it keeps playing whatever music is loaded on the minimoog while being in somebody's hand

**Why is this bad/What are the consequences:**
It's not really an important issue, it's just weird that a drone can use it's tiny arms to play music from across the ship. 
**Steps to reproduce the problem**:
1. Be Drone.
2. Get a carbon to pick you up, probably from over 1 tile away from the minimoog
3. Get put on head, enjoy hearing the toy story theme while your new human parades you around the bar

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Nothing major here, it's just kinda derp that it can happen.

**Comment by Kmc2000** [comment]
I thought the minimoog played songs automatically? and that only the piano needed to be close to you..

**Comment by AuroranAI** [comment]
Nope, minimoogs stop playing like any other instrument when you leave the area around it.
