### ISSUE TITLE
Round start shenanigans

### ISSUE THREAD

**Issue by Idontcareacount** [FTL13/FTL13#750]
**Problem Description**:
Random teleportation and apparent reequip of starting items as botanist. 

**What did you expect to happen**: 
Well, for starters, there are very few scenarios were you teleport across the ship at round start, and secondly, I'm pretty sure having two PDA's isn't a feature either.

**What happened instead**:
Well...... exactly what i described..... isn't this part of the sheet a little redundant? 

**Why is this bad/What are the consequences:**
Well... not really an ISSUE per se, more of strange space magic. 

**Steps to reproduce the problem**:
Right after round start, i eagerly click "Join Game" and choose botanist. Soon after that i began walking down hall, and before even making it to tool storage, i was whipped away by space magic all the way to botany, and got a second PDA with no id or cart..... so that's cool i guess....

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Extended game mode, Round number 533, server time round start, blahblahblah.

**Comment by Psyentific** [comment]
i've run into this as well, as captain.

seems to happen when you join in the few seconds between round start and everyone spawning in w/ equipment.
