### ISSUE TITLE
Invisible Monkeys persist in harassing some crew after leaving a habitable world.

### ISSUE THREAD

**Issue by Shuffl3** [FTL13/FTL13#760]
What is the problem?
Got wrekd by monkeys I couldn't observe or interact with.

Why do you think this is a bug?
The new exoplanet code is pretty fresh, and there would of been more publicity about introducing hordes of Pred-Monkeys.

How is what happened different from what you expected?
I expected monkeys to at least reflect visible light.

Why do you think this is an important issue?
Kinda ruins the remainder of the round for whomever is affected. Cloning would probably reset monkey agro, but players shouldn't have to resort to that.

The most important section. Review everything you did leading up to causing the issue.
1. Ship lands on exoplanet with jungle world and multiude monkey hordes.
2. Engage monkey hordes in combat. 
3. Leave planet/system on the ship.
4. Await red walls of attack text

Anything else you can tell us.
![image](https://cloud.githubusercontent.com/assets/25386943/25579063/faa7b156-2e39-11e7-8540-b0d73e33a75b.png)

I seemed to be the only one affected.
Monkeys didnt seem to care where I was or what z level I was on aside from when I took the q-pad back to the exoplanet.

**Comment by Qustinnus** [comment]
@monster860 does Z level unloading properly remove mobs?
