### ISSUE TITLE
Supermatter doesn't generate enouf heat fast enouf.

### ISSUE THREAD

**Issue by Koekiegast** [FTL13/FTL13#768]
**Problem Description**:
The suermatter doesn't generate enouf heat fast enouf.

**What did you expect to happen**: 
I expectet the supermatter would power the ship by generating enouf heat.

**What happened instead**:
It       was   so      slow    heating      up.
**Why is this bad/What are the consequences:**
Because the supermatter is suposed to power the ship, good luck doing that with a -140 degrees hot loop.

**Steps to reproduce the problem**:
Set up the supermatter nothing fancy needed, get the cold loop running good, inject n2o into the hot loop, turn on emmiter, watch the power output and the heat in the hot loop climb slower then a snail climbing the Burj Khalifa.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: It was the begining of the round.

**Comment by ninjanomnom** [comment]
Fixed in #https://github.com/FTL13/FTL13/pull/757

**Comment by ike709** [comment]
>enouf
