### ISSUE TITLE
No Atmosphere/Pressure in R&D

### ISSUE THREAD

**Issue by DoDoNat** [FTL13/FTL13#775]
**Problem Description**:
What is the problem?
There is no atmosphere/pressure in R&D

**What did you expect to happen**: 
Why do you think this is a bug?
I expected pressure to be equalised

**What happened instead**:
How is what happened different from what you expected?
R&D just stays at Nan Pressure

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Can't survive in no pressure without a hardsuit

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Location was repeatably drained due to combat damage

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.
Happened around same time as Robotics was fixed with power

**Comment by ike709** [comment]
Robotics was hit earlier by an enemy ship and hadn't repressurized. Not a bug.
