### ISSUE TITLE
PDA messages missing reply button and newline

### ISSUE THREAD

**Issue by NIXC** [FTL13/FTL13#777]
**Problem Description**:
What is the problem?
When receiving PDA messages the reply button and the new line are missing
**What did you expect to happen**: 
Why do you think this is a bug?
At the very least the new line should have been there.
**What happened instead**:
How is what happened different from what you expected?
![image](https://cloud.githubusercontent.com/assets/16856738/25768477/0a3fc56e-31c2-11e7-8797-54d4ebc5a819.png)
You can clearly see its not right.
**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
It ruins my immersion. 
**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Receive a PDA message.

**Comment by ike709** [comment]
Probably my fault.
