### ISSUE TITLE
PDA bug during ftl

### ISSUE THREAD

**Issue by Stealthkibbler** [FTL13/FTL13#785]
If you get a PDA message and then the Ship starts to shudder through FTL the message doesn't skip a line

**Comment by ike709** [comment]
You sure it's not just #777 and the server hadn't been updated yet? Or is this an extremely weird edge case?

**Comment by Vivalas** [comment]
Has this still been reproduced?

**Comment by Wulfestwulf** [comment]
I am just going to guess this is not a issue
