### ISSUE TITLE
No ore boxes for miners

### ISSUE THREAD

**Issue by yobob591** [FTL13/FTL13#79]
**Problem Description**:
No ore boxes for miners

**What did you expect to happen**: 
ore boxes

**What happened instead**:
no ore boxes

**Why is this bad/What are the consequences:**
cant collect ores efficiently

**Steps to reproduce the problem**:
be on map

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by monster860** [comment]
Finding space for it would be a bit of a challenge.

**Comment by Vivalas** [comment]
To add on to this there doesn't seem to be a way to process ore either.
