### ISSUE TITLE
People not on ship get deleted when changing star systems

### ISSUE THREAD

**Issue by yobob591** [FTL13/FTL13#80]
**Problem Description**:
People  get deleted when changing star systems
**What did you expect to happen**: 
People to keep existing

**What happened instead**:
Person stopped existing

**Why is this bad/What are the consequences:**
They are dead, have to wait and do nothing while they mine

**Steps to reproduce the problem**:
Leave someone in space/mining

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us. I get that you cant leave all sectors loaded, but you should stop the ship from jumping or at least display a warning before you kill someone

**Comment by monster860** [comment]
There's a portable relay in the mining room for a reason: If you wrench it down in a planet rings, and turn it on with a multitool, then it will keep the z-level loaded.

**Comment by yobob591** [comment]
Oh thanks
