### ISSUE TITLE
Unable to establish a connection: You're too far away from the station!

### ISSUE THREAD

**Issue by yobob591** [FTL13/FTL13#81]
**Problem Description**:
Comms console spams this

**What did you expect to happen**: 
Useable comms console

**What happened instead**:
Not usable

**Why is this bad/What are the consequences:**
Cant call shuttle, cant say dank craptain announcements

**Steps to reproduce the problem**:
Fly around for a bit, fight some ships, get shot up, buy some stuff, Im not sure what exactly caused it

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by monster860** [comment]
God damn it, I thought I fixed that.

**Comment by CrAzYPiLoT-SS13** [comment]
You did, a part of it.
[This](https://github.com/FTL13/FTL13/blob/master/code/game/machinery/computer/communications.dm#L354 ) is the cause.
