### ISSUE TITLE
There is no state law button.

### ISSUE THREAD

**Issue by Maxiemo** [FTL13/FTL13#82]
**Problem Description**:
AI Cannot state laws

**What did you expect to happen**: 
I expected to state laws

**What happened instead**:
I was unable to state laws

**Why is this bad/What are the consequences:**
Laws were not stated

**Steps to reproduce the problem**:
State laws

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: I JUST WANT TO STATE LAWS

**Comment by CrAzYPiLoT-SS13** [comment]
There is one.
