### ISSUE TITLE
Gravity Gen still doesn't work in transit

### ISSUE THREAD

**Issue by CrAzYPiLoT-SS13** [FTL13/FTL13#83]
What it says on the tin.

@monster860

**Comment by CrAzYPiLoT-SS13** [comment]
Seems it only doesn't work on first jump, subsequent jumps are fine.

**Comment by Crazylemon64** [comment]
https://github.com/FTL13/FTL13/blob/master/code/game/area/areas.dm#L347-L359
This is the code for checking if an atom has gravity.

How is the gravity generator transferred from level to level?

**Comment by Xxxretroxgears3** [comment]
not sure but this caused my own server to crash? Not sure if it is the same thing
