### ISSUE TITLE
Space line

### ISSUE THREAD

**Issue by Koekiegast** [FTL13/FTL13#833]
**Problem Description**:
There was a line of space on a planet.

**What did you expect to happen**: 
There should be planet there.

**What happened instead**:
There was a line of space

**Why is this bad/What are the consequences:**
Space sucks up air and is cold and dangerous.

**Steps to reproduce the problem**:
Land on a (lava) planet with shields on, diable shields, look south of ship.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: It was on a lava planet and i think under the shields.

**Comment by ninjanomnom** [comment]
probably fixed, new shuttle code new bugs
