### ISSUE TITLE
Salvage Maps Getting Into the Ship

### ISSUE THREAD

**Issue by Siderivers** [FTL13/FTL13#834]
**Problem Description**:
What is the problem?

Salvage maps appear right on the ship, mostly on botany, library, kitchen, and maintenance,  as seen happening here. 

https://puu.sh/w2OAn/22025e5737.png
https://puu.sh/w2Prd/20e2610c76.png
https://puu.sh/w2PyG/ac0e3bbdad.png

After the ship jumps, it'll leave a hole that can't be patched up as anything on the area where the map was will disappear after jumping somewhere else. Here I suspect that it'll disappear to another z-level because at the time of taking the above three pictures, somebody on the salvage area was jumped into another level with the salvage and the ship being left with a hole looking where the salvage map was. 
https://puu.sh/w2Wly/df75865cee.png
https://puu.sh/w2PJi/696355e718.png

And here it is with a part of the shield cut off that will stay like that even if the shield were to be turned off and reactivated.
https://puu.sh/w2PQD/dbbc1a4aac.png

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.

This happened while the ship was docked on a station. I have no idea if it happens while it's undocked.  I have no idea how exactly to reproduce this other than noticing that the ship was docked on a station.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

Extended and I noticed this happens during a ship battle while the ship itself was docked on a station.

**Comment by ike709** [comment]
Should be fixed in the rebase.

@ninjanomnom

**Comment by ninjanomnom** [comment]
I don't touch salvage map spawning, so no idea
