### ISSUE TITLE
Kitty issue

### ISSUE THREAD

**Issue by CrAzYPiLoT-SS13** [FTL13/FTL13#84]
SCHRODINGER IS LEFT FLOATING EVEN AFTER GRAVITY IS BACK ON. PLS FIX LATERALLY UNPLAYABLE

**Comment by monster860** [comment]
Is schrodinger the only mob left floating after gravity returns?

**Comment by CrAzYPiLoT-SS13** [comment]
No, that would be all simple animals/pets on the station.

**Comment by ickata1** [comment]
Removing pets from the ship and adding more clowns is a simple way to fix this

**Comment by coolsurf6** [comment]
Clowns don't fix anything! ERRRYONE PANIC!!!!!!!

**Comment by Vivalas** [comment]
Maybe he just switches between quantum states of floating and not floating?
