### ISSUE TITLE
Cloning memes

### ISSUE THREAD

**Issue by Idontcareacount** [FTL13/FTL13#841]
**Problem Description**:
Cloned a plasmaman, into a human

**What did you expect to happen**: 
Well generally speaking, cloners aren't supposed to race change, let alone is it normal for a plasmameme to suddenly transform into a human.

**What happened instead**:
Wow, let me quickly restate myself

**Why is this bad/What are the consequences:**
MAH MURSIONZ REEEEE

**Steps to reproduce the problem**:
~~Take a dead plasma man, stuff um in a cloner, try to shove them into the shower, but keep slipping like a doof, have two consecutive failed key reassignments(bodies were cloned catatonic), have one successful clone, and then kill it, and then use that to clone, and you'll get yourself a hooman bean. 
It was probably just a freak bug anyways.~~
Badmins reeee

**Possibly related stuff** (which gamemode was it? What were you doing at the time?):
Was Probably in ftl, round 649, station time 13:05-ish, server time: 2017-06-04 01:00-ish, cloned person was Iron LXIX, probably haven't detailed out the full scene, but that's as much as i care to explain.

**Comment by ike709** [comment]
I was change by a badmin you meme, not a bug.

**Comment by Idontcareacount** [comment]
Okay then
how do resolve own issue

**Comment by ike709** [comment]
...

**Comment by ike709** [comment]
Click close.
