### ISSUE TITLE
Broken tendrils

### ISSUE THREAD

**Issue by MASMC** [FTL13/FTL13#843]
**Problem Description**:
What is the problem?
Well you see, a tendril got into space as it was right on the shield. Like, right on top of it. When the ship took off, it came with it. A sec officer killed it, and this. It kind of... made a chasm... in space... which the shield fell into...
![image](https://cloud.githubusercontent.com/assets/9438930/26767167/4261b84c-496b-11e7-8622-5c646989f88b.png)

**What did you expect to happen**: 
Why do you think this is a bug?
WELL. Let's see. Chasm in space? And the shield falling into said chasm?

**What happened instead**:
How is what happened different from what you expected?
WELL YOU SEE. EVERYTHING.

**Why is this bad/What are the consequences:**
Why do you think this is an important issue?
Would YOU want to fall into a space chasm?

**Steps to reproduce the problem**:
The most important section. Review everything you did leading up to causing the issue.
Tendril in spaces
Kill it
Watch and cri everytiem

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by ninjanomnom** [comment]
`a tendril got into space through stuff happening`

Need a bit more description than that

**Comment by AuroranAI** [comment]
Chances are this is related to how when the ship lifts off, any entities that are inside of the field get taken with it.
Tendrils normally aren't close enough to the ship to get picked up, but it seemed this one did? It's origin seems to be right on top of the shield. When the Tendril was killed, spawned the chasm.

**Comment by GeneralGoose** [comment]
a week ago i saw a chasm *inside* the ship
it took out a chunk of it and 1 borg and 2 other players including captain jumped into it 
however when the ship moved, chasm wasn't moved with it and there just was a hole there
chasm was in the ship, but didnt touch the shields

**Comment by MASMC** [comment]
Yeah, the chasm is stuck on the original Z-Level. If you go back to where it was, the exact same thing happens again, tested on private server.

**Comment by ninjanomnom** [comment]
probably fixed, new shuttle code new bugs
