### ISSUE TITLE
Gravity Issue

### ISSUE THREAD

**Issue by Xxxretroxgears3** [FTL13/FTL13#87]
**Problem Description**:
After jumping there is not gravity even if the generator is on
**What did you expect to happen**: 
Grav to be on
**What happened instead**:
NO Grab
**Why is this bad/What are the consequences:**
Its Game Breaking
**Steps to reproduce the problem**:
FTL jump
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Crazylemon64** [comment]
Copy of #83
