### ISSUE TITLE
Ore Issue

### ISSUE THREAD

**Issue by Xxxretroxgears3** [FTL13/FTL13#88]
**Problem Description**:
Only Silver can be mined
**What did you expect to happen**: 
You cannot get anything else besides silver
**What happened instead**:
I expected to get other ores
**Why is this bad/What are the consequences:**
You Cannot R&D
**Steps to reproduce the problem**:
Jump to ringed planet and mine.
**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by monster860** [comment]
Every ringed planet contains a unique mineral composition. Try finding a different planet.
