### ISSUE TITLE
Kill a target mission awards completion for miners in different maps

### ISSUE THREAD

**Issue by TatsumakiMagi** [FTL13/FTL13#89]
**Problem Description**:
If your mission is to kill a target and they go onto a meteor and the ship moves to a different map your objective will be completed even though the person is alive.

**What did you expect to happen**: 
Failed the objective as I was not dead

**What happened instead**:
Individual completed their objective despite me being alive

**Why is this bad/What are the consequences:**
Gives antagonists greentext when they didn't complete objectives.

**Steps to reproduce the problem**:
Move to the ringed planet, step out of the ship with the relay on the meteor, have the ship leave. If the round ends with you still on the meteor even if you are alive the antag will be rewarded the completion for killing you. 

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by coolsurf6** [comment]
Thas normal as they are left stranded for dead... Rip miner!

**Comment by TatsumakiMagi** [comment]
That would make sense I guess, although I was in a survival pod which had an environmental module, comfy chair, donk pockets and a sweet acoustic guitar. Felt very alive! (and cosy.)

**Comment by CrAzYPiLoT-SS13** [comment]
This should be fixed with the relay thing implementation.
