### ISSUE TITLE
No secret documents are on the ship

### ISSUE THREAD

**Issue by TatsumakiMagi** [FTL13/FTL13#90]
**Problem Description**:
There are no secret documents to steal on the ship

**What did you expect to happen**: 
The secret documents would be somewhere on the ship

**What happened instead**:
There are no secret documents on the ship

**Why is this bad/What are the consequences:**
Some antag objectives give a task to steal the secret documents, if they do not spawn this can not be completed

**Steps to reproduce the problem**:
Gain the antag objective of stealing the documents, it is impoosible as they do not spawn.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by monster860** [comment]
Also needs nuke and nuke disk.

**Comment by Vivalas** [comment]
On a local test I put the nuke in the AI core where the AI goes, looked pretty cool
