### ISSUE TITLE
Computer in munitions doesn't do anything

### ISSUE THREAD

**Issue by TatsumakiMagi** [FTL13/FTL13#95]
**Problem Description**:
The computer in the munitions department doesn't do anything when clicked on

**What did you expect to happen**: 
Computer should have some utility, not sure what it's intended purpose is though.

**What happened instead**:
Clicking the computer does nothing.

**Why is this bad/What are the consequences:**
Can't use this computer.

**Steps to reproduce the problem**:
Join server as munitions officer and attempt to use the computer in the munitions area.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Vivalas** [comment]
This is not a but, it is currently a placeholder and will be added in the MAC update.

**Comment by CrAzYPiLoT-SS13** [comment]
I'll be leaving this labeled as a bug, since I'm too lazy to make a new, more specific label

**Comment by monster860** [comment]
God damn it.... @Vivalas, You need to have "fixes" "fix" "fixed" "closes" "close" "closed" "resolve" "resolves" "resolved" before the issue ID if you want it to actually be closed when your PR is merged.

**Comment by Vivalas** [comment]
Derp. I know that though, I do it all the time for minor bugfixes.
