### ISSUE TITLE
You can't return to orbit from a planet

### ISSUE THREAD

**Issue by ike709** [FTL13/FTL13#968]
You can't return to orbit after landing, but you can dock with a station orbiting the planet or FTL jump

**Comment by AuroranAI** [comment]
Duplicate of #851

**Comment by AuroranAI** [comment]
Adding on to this: from the initial dock, you can land on the planet and go back into orbit, but you can't go back to dock after landing, or go back to the planet after going to orbit.

**Comment by ike709** [comment]
Fixed
