### ISSUE TITLE
Using screw driver on Engine emitter causes it to turn

### ISSUE THREAD

**Issue by TatsumakiMagi** [FTL13/FTL13#97]
**Problem Description**:
When you use a screwdriver on the emitter in the engine room the emitter will turn from west facing to east facing. When the panel is closed again via screwdriver the emitter turns back to the normal direction.

**What did you expect to happen**: 
The emitter to stay facing the original direction

**What happened instead**:
The emitter rotated

**Why is this bad/What are the consequences:**
It's only a visual problem, not too huge an issue other than confusion. 

**Steps to reproduce the problem**:
Started round as engineer, used a screwdriver on the emitter as it was not firing due to low power. Emitter flipped around.

**Possibly related stuff (which gamemode was it? What were you doing at the time? Was
anything else out of the ordinary happening?)**: Anything else you can tell us.

**Comment by Vivalas** [comment]
This might be related to #33.

**Comment by Vivalas** [comment]
99% sure this is fixed. :tm:

**Comment by Funce** [comment]
@Vivalas Pretty Fixed alright.
